### ISSUE TITLE
Was there any reason for post format titles to be smaller than the standard post titles?

### ISSUE THREAD

**Issue by maharzan** [WordPress/twentysixteen#101]
It looks like post formats are a part of standard posts because of the font size differences..

**Comment by iamtakashi** [comment]
The reason is to take away focus from the title to make the content prominent.

**Comment by maharzan** [comment]
Hmm.. Is there any post format specific design on this theme? I didn't see any. The small titles make the whole thing look like its a part of the top "standard" post on archive pages. esp, when you have one standard post on the top and all post formats in the bottom. The test data especially makes this prominent. I was thinking how long that post was...

**Comment by iamtakashi** [comment]
> Is there any post format specific design on this theme
- A post that has a format displays tis format in the meta.
- Small titles
- Status format hides the title.

That's it. There is no special design treatments in this theme. We have another discussion about the fate of post formats in this theme, #45. I'm closing this because kind of duplicated.
