### ISSUE TITLE
Margin on the right

### ISSUE THREAD

**Issue by maharzan** [WordPress/twentysixteen#104]
While resizing, I noticed there was a certain window of width where there is margin on the right side. The header, menu and footer menu seems to extend full width but the content seems to cover like 75%. Is this done deliberately for "readability" ? 

![space](https://cloud.githubusercontent.com/assets/883993/9662777/cffe7304-5280-11e5-948d-16f3ad4b2533.png)

**Comment by iamtakashi** [comment]
Yes. That's correct.
