### ISSUE TITLE
Redundant selectors in bigImageClass() of js/functions.js

### ISSUE THREAD

**Issue by tywayne** [WordPress/twentysixteen#105]
Inside the `.each()` iterator on found images, we have redundant `$( this )` selectors, even though we cached it in the `img` variable. While the performance costs of creating a few more instances of a jQuery object here probably won't make much difference, it is best practice to use the stored instance.

Also, in the same `bigImageClass()` function, we use the `img` var as a selector like `$( img )` when `img` is already a jQuery object. 

Will add a PR shortly.

**Comment by iamtakashi** [comment]
The PR looks great. Thank you! Can you add you **WordPress.org** username to the CONTRIBUTORS.md?

**Comment by iamtakashi** [comment]
nvm. Your name is now in with the fix for #67.
