### ISSUE TITLE
Inconsistent spacing in multi-line var declarations across js files

### ISSUE THREAD

**Issue by tywayne** [WordPress/twentysixteen#107]
I know "whitespace only" code refactoring changes for core files are discouraged, but this isn't in core yet so I felt it should at least be noted.

Some multi-line var declarations use spaces to indent the next line, while others correctly use tabs (according to the [Javascript coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/javascript/#declaring-variables-with-var)). 

> Assignments within the var statement should be listed on individual lines, while declarations can be grouped on a single line. Any additional lines should be indented with an additional tab.

Offending files include:
- `/js/functions.js`
- `/js/customize-preview.js`
- `/js/skip-link-focus-fix.js`

**Comment by karmatosed** [comment]
Can you do a patch for this?

**Comment by tywayne** [comment]
@karmatosed Sure thing, PR sent.
