### ISSUE TITLE
dropdown-toogle and usability on mobile devices (googles guidelines)

### ISSUE THREAD

**Issue by MonikaTS** [WordPress/twentysixteen#111]
the easiest way 
style.css line 818 
.main-navigation .menu-item-has-children > a {
    /_padding-right: 48px;_/
    margin-right:48px;
}

for desktop 
style.css line 2933
    .main-navigation ul ul .menu-item-has-children > a {
        padding-right: 2.0625em;
        margin-right:0;
    }

![twenty-sixteen-dropdown-toggle](https://cloud.githubusercontent.com/assets/12694170/9698275/3f8d940a-53af-11e5-8dff-3df70f925b9d.png)
![twenty-sixteen-dropdown-toggle-ok](https://cloud.githubusercontent.com/assets/12694170/9698277/42f088aa-53af-11e5-90d4-213a6419b387.png)

**Comment by karmatosed** [comment]
HI @MonikaTS, can you explain why you are suggesting this? Unfortunately your image linked was not in English so I am having trouble working out what you are suggesting.

**Comment by iamtakashi** [comment]
I've done the test myself. In English Google says...

![screen-shot-2015-09-05-at-11 47 07](https://cloud.githubusercontent.com/assets/908665/9698915/49a4de0c-53c4-11e5-8804-912c25593f7a.png)

I'll work on a patch.

**Comment by MonikaTS** [comment]
thanks @iamtakashi  I can't take screens in englisch 
I have no time to repair  "failure  class url fn" => entry-footer with many categories and tags  this weekend, but I will do it next week

**Comment by iamtakashi** [comment]
@MonikaTS, what's your WordPress.org username? I'll add your name in my patch since your suggestion makes sense.

The issue with entry-footer is a separate issue, so could you open a new one when you have a time? Let's keep this for only the dropdown button.

**Comment by MonikaTS** [comment]
@karmatosed  my WP username is Monika 
my profile page  https://profiles.wordpress.org/monika/

and yes I will open a new issue with "entry-footer" with many categories and tags :-)
I try to find an "aesthic" way
