### ISSUE TITLE
Post navigation shows black square when on the last page

### ISSUE THREAD

**Issue by Nikschavan** [WordPress/twentysixteen#114]
![Black Square](http://i.imgur.com/nvjOPYy.jpg)

**Comment by ihorvorotnov** [comment]
Discussed in #76. Closed, because it's a design pattern:

> This is intentional to have the un-clickable square without arrow to have the balance.

**Comment by iamtakashi** [comment]
Yes, that's correct. But it'd be great If we can come up with an elegant solution to make the `.prev`link to the right-end on the last page though.

**Comment by ihorvorotnov** [comment]
That was the first idea I though of. These squares are ::before elements, can't figure out yet how to remove that last one if there's no more pages. Will look into it, if you don't insist it's a design choice.

**Comment by maharzan** [comment]
The block definitely misleads as a "clickable item". Doesn't seem to fix with just CSS so added a little jQuery.

**Comment by xavortm** [comment]
Why not add right arrow, but make it like 80% transparent to indicate that this is not a bug and that clearly there are no more pages? That way you will also keep the balance.

**Comment by karmatosed** [comment]
What was the CSS only hurdle?

**Comment by maharzan** [comment]
The elements are absolutely positioned so without knowing the "last page" there is no way to move that prev arrow to the right side. Not sure if we can find that with CSS only.

**Comment by xavortm** [comment]
Yes you can easily do that by adding this style to the :before (the black square):
https://gist.github.com/xavortm/15a93caab9b3b17cb4fe 

That way you will always have the darker arrow (showing that its not available) and when it is, it will be overlapped by the <a> element linking right. So by this you are covered that you cant click it when its unavailable.

**Comment by ihorvorotnov** [comment]
I also couldn't fix it with css only, so passed it to my fellow front-end dev. Easy to fix with jQuery / javascript, however, I don't like using scripts for such cases.

**Comment by karpstrucking** [comment]
I like @xavortm's suggestion

![image](https://cloud.githubusercontent.com/assets/999261/9720472/6e03a172-555c-11e5-9565-824e00729eca.png)

**Comment by iamtakashi** [comment]
Do we want to add a non-clickable button with a semi-transparent arrow on the first page like this?

![screen shot 2015-09-07 at 17 37 58](https://cloud.githubusercontent.com/assets/908665/9720594/5b54e65a-5587-11e5-89b4-49d96fd1fc01.png)

**Comment by karpstrucking** [comment]
probably should for consistency

**Comment by ihorvorotnov** [comment]
:+1:
