### ISSUE TITLE
Nested menu in far right position runs under vertical scroll bar

### ISSUE THREAD

**Issue by brentlogan** [WordPress/twentysixteen#123]
If the rightmost menu is nested, a portion of the nested menu hides behind the vertical scroll bar. 

![menu bug](https://cloud.githubusercontent.com/assets/14060692/9709180/94568c44-54db-11e5-9b50-3db57863dbc2.jpg)

I see this behavior with both Chrome and Edge browsers.

**Comment by karmatosed** [comment]
This seems to happen on a mid screen size @iamtakashi.

**Comment by iamtakashi** [comment]
We've talked about this in #112. It's a limitation of the design.

**Comment by karmatosed** [comment]
Let's close this one up then.
