### ISSUE TITLE
Version 1.0

### ISSUE THREAD

**Issue by maharzan** [WordPress/twentysixteen#132]
I am sure this is scheduled but just wanted to make note of it here. Everywhere there is  `@since Twenty Sixteen 1.0` but the style.css has a different version. Plus, I noticed that the wordpress.org version is more latest ( rendering date? ) than here. I was getting an update message over at the Themes page and was wondering if my fork wasn't upto date. :)

**Comment by karmatosed** [comment]
Once the theme gets released things will work out with version numbers. The update message is because of the difference between GitHub and the .org theme directory. This is something we're working on.
