### ISSUE TITLE
Better show/hide of .byline in .entry-footer

### ISSUE THREAD

**Issue by tywayne** [WordPress/twentysixteen#135]
In `twentysixteen_entry_meta()` the .byline section is added for posts.
This section is then hidden by default with css ([style.css - L1919](https://github.com/WordPress/twentysixteen/blob/master/style.css#L1919)) and only shown again (as far as I can tell) if viewing a single post or if we're on a multi author blog ([style.css - L1924](https://github.com/WordPress/twentysixteen/blob/master/style.css#L1924)).

Would it be better to just adjust the logic in `twentysixteen_entry_meta()` to only output the .byline markup in the desired scenarios?

Something like `if ( 'post' == get_post_type() && ( is_multi_author() || is_single() ) )`

**Comment by karmatosed** [comment]
Noting this is flagged for discussion in the next meeting: Friday 16:00 UTC in #core-themes.

**Comment by SergeyBiryukov** [comment]
Twenty Fifteen [does the same](https://core.trac.wordpress.org/browser/tags/4.3/src/wp-content/themes/twentyfifteen/inc/template-tags.php#L82), so makes sense to me.

**Comment by iamtakashi** [comment]
My initial thought was that in this way, people can show or hide there avatar with just simple CSS changes but I'm not against with the idea of not printing at all either.

If we go this way, we should get rid of `group-blog` body class as well as some more style rules related to `byline`.

**Comment by karmatosed** [comment]
As discussed in today's chat, we're going to keep this as it is for now because it provides more flexibility using just CSS.
