### ISSUE TITLE
RTL- SITE TITLE issue(Design)

### ISSUE THREAD

**Issue by weblizar** [WordPress/twentysixteen#138]
When you switched to RTL-mode the Site Title and the Menus , Depicts distorted design.

Also TAGS / Edit option should be on the RIGHT side of page.

Screenshot attached for both

![2016-rtl](https://cloud.githubusercontent.com/assets/14194709/9761096/16cb6846-5718-11e5-8236-1d42c7b718ce.png)

Thanks.

**Comment by iamtakashi** [comment]
RTL support is scheduled task but not yet implemented. See #5.

**Comment by weblizar** [comment]
Thanks for the info..
