### ISSUE TITLE
Fix some coding standards errors, reported by Travis CI

### ISSUE THREAD

**Issue by ihorvorotnov** [WordPress/twentysixteen#143]
As @karmatosed asked in #139, after adding Travis CI checks we've got some errors in our current codebase. It's mostly js-related, some minor php stuff. Nothing critical.

I have a day-off tomorrow (well, in 10-12 hours) - can do it if no one is going to take care of it earlier.

**Comment by philiparthurmoore** [comment]
I'll have a lot of this sussed out as well if you don't get around to it.
Thanks so much for helping with this and for engaging that discussion. Big
thumbs up.

**Comment by karmatosed** [comment]
Having one PR to fix PHP and one to fix JS could be nice - just as a thought rather than a mass PR. Thanks for taking this on. Be great to get it so tests can be passed.

**Comment by philiparthurmoore** [comment]
PHP is done.

JS is all that remains! Super-close.

**Comment by karmatosed** [comment]
Awesome, want to do two seperate PR @philiparthurmoore ?

**Comment by philiparthurmoore** [comment]
I mean that PHP was done in #139 and #146, so no more PHP errors exist at all in the theme.

JS coding standards are all that remain. I'll put a PR together for JS tomorrow if @ihorvorotnov doesn't get around to it:

```
Line comments must be preceded with a blank line at ./js/color-scheme-control.js :
    25 |  ready: function() {
    26 |   if ( 'color_scheme' === this.id ) {
    27 |    this.setting.bind( 'change', function( value ) {
------------------------------------------------------------^
    28 |     // Update Background Color.
    29 |     api( 'background_color' ).set( colorScheme[value].colors[0] );

All identifiers must be camelCase or UPPER_CASE at ./js/color-scheme-control.js :
    71 |
    72 |  // Add additional color.
    73 |  colors.border_color = Color( colors.main_text_color ).toCSS( 'rgba', 0.1 );
-----------------^
    74 |
    75 |  css = cssTemplate( colors );

All identifiers must be camelCase or UPPER_CASE at ./js/color-scheme-control.js :
    71 |
    72 |  // Add additional color.
    73 |  colors.border_color = Color( colors.main_text_color ).toCSS( 'rgba', 0.1 );
----------------------------------------------^
    74 |
    75 |  css = cssTemplate( colors );

Line comments must be preceded with a blank line at ./js/functions.js :
     9 | var $body, masthead, menuToggle, siteNavigation, socialNavigation, siteHeaderMenu, resizeTimer;
    10 |
    11 | function initMainNavigation( container ) {
---------------------------------------------------^
    12 |  // Add dropdown toggle that display child menu items.
    13 |  container.find( '.menu-item-has-children > a' ).after( '<button class="dropdown-toggle" aria-expanded="false">' + screenReaderText.expand + '</button>' );

Not yoda condition at ./js/functions.js :
    25 |   _this.toggleClass( 'toggled-on' );
    26 |   _this.next( '.children, .sub-menu' ).toggleClass( 'toggled-on' );
    27 |   _this.attr( 'aria-expanded', _this.attr( 'aria-expanded' ) === 'false' ? 'true' : 'false' );
----------------------------------------^
    28 |   _this.html( _this.html() === screenReaderText.expand ? screenReaderText.collapse : screenReaderText.expand );
    29 |  } );

Line comments must be preceded with a blank line at ./js/functions.js :
    38 |
    39 | // Enable menuToggle.
    40 | ( function() {
-----------------------^
    41 |  // Return early if menuToggle is missing.
    42 |  if ( ! menuToggle ) {

Not yoda condition at ./js/functions.js :
    49 |  menuToggle.on( 'click.twentysixteen', function() {
    50 |   $( this ).add( siteHeaderMenu ).toggleClass( 'toggled-on' );
    51 |   $( this ).add( siteNavigation ).add( socialNavigation ).attr( 'aria-expanded', $( this ).add( siteNavigation ).add( socialNavigation ).attr( 'aria-expanded' ) === 'false' ? 'true' : 'false');
------------------------------------------------------------------------------------------^
    52 |  } );
    53 | } )();

Missing space before closing round bracket at ./js/functions.js :
    49 |  menuToggle.on( 'click.twentysixteen', function() {
    50 |   $( this ).add( siteHeaderMenu ).toggleClass( 'toggled-on' );
    51 |   $( this ).add( siteNavigation ).add( socialNavigation ).attr( 'aria-expanded', $( this ).add( siteNavigation ).add( socialNavigation ).attr( 'aria-expanded' ) === 'false' ? 'true' : 'false');
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------^
    52 |  } );
    53 | } )();

Variable declarations must be the first statements of a function scope. at ./js/functions.js :
   108 |  }
   109 |
   110 |  var entryContent = $( '.entry-content' );
----------^
   111 |  entryContent.find( 'img.size-full' ).each( function() {
   112 |   var img                  = $( this ),

Not yoda condition at ./js/keyboard-image-navigation.js :
     8 |
     9 |  // Left arrow key code.
    10 |  if ( e.which === 37 ) {
---------------^
    11 |   url = $( '.nav-previous a' ).attr( 'href' );
    12 |

Not yoda condition at ./js/keyboard-image-navigation.js :
    12 |
    13 |  // Right arrow key code.
    14 |  } else if ( e.which === 39 ) {
----------------------^
    15 |   url = $( '.nav-next a' ).attr( 'href' );
    16 |  }

All identifiers must be camelCase or UPPER_CASE at ./js/skip-link-focus-fix.js :
     7 |
     8 | ( function() {
     9 | var is_webkit = navigator.userAgent.toLowerCase().indexOf( 'webkit' ) > -1,
-------------^
    10 |  is_opera  = navigator.userAgent.toLowerCase().indexOf( 'opera' )  > -1,
    11 |  is_ie     = navigator.userAgent.toLowerCase().indexOf( 'msie' )   > -1;

All identifiers must be camelCase or UPPER_CASE at ./js/skip-link-focus-fix.js :
     8 | ( function() {
     9 | var is_webkit = navigator.userAgent.toLowerCase().indexOf( 'webkit' ) > -1,
    10 |  is_opera  = navigator.userAgent.toLowerCase().indexOf( 'opera' )  > -1,
----------^
    11 |  is_ie     = navigator.userAgent.toLowerCase().indexOf( 'msie' )   > -1;
    12 |

All identifiers must be camelCase or UPPER_CASE at ./js/skip-link-focus-fix.js :
     9 | var is_webkit = navigator.userAgent.toLowerCase().indexOf( 'webkit' ) > -1,
    10 |  is_opera  = navigator.userAgent.toLowerCase().indexOf( 'opera' )  > -1,
    11 |  is_ie     = navigator.userAgent.toLowerCase().indexOf( 'msie' )   > -1;
----------^
    12 |
    13 | if ( ( is_webkit || is_opera || is_ie ) && document.getElementById && window.addEventListener ) {

All identifiers must be camelCase or UPPER_CASE at ./js/skip-link-focus-fix.js :
    11 |  is_ie     = navigator.userAgent.toLowerCase().indexOf( 'msie' )   > -1;
    12 |
    13 | if ( ( is_webkit || is_opera || is_ie ) && document.getElementById && window.addEventListener ) {
----------------^
    14 |  window.addEventListener( 'hashchange', function() {
    15 |   var id = location.hash.substring( 1 ),

All identifiers must be camelCase or UPPER_CASE at ./js/skip-link-focus-fix.js :
    11 |  is_ie     = navigator.userAgent.toLowerCase().indexOf( 'msie' )   > -1;
    12 |
    13 | if ( ( is_webkit || is_opera || is_ie ) && document.getElementById && window.addEventListener ) {
-----------------------------^
    14 |  window.addEventListener( 'hashchange', function() {
    15 |   var id = location.hash.substring( 1 ),

All identifiers must be camelCase or UPPER_CASE at ./js/skip-link-focus-fix.js :
    11 |  is_ie     = navigator.userAgent.toLowerCase().indexOf( 'msie' )   > -1;
    12 |
    13 | if ( ( is_webkit || is_opera || is_ie ) && document.getElementById && window.addEventListener ) {
-----------------------------------------^
    14 |  window.addEventListener( 'hashchange', function() {
    15 |   var id = location.hash.substring( 1 ),


17 code style errors found.
```

Those are what we'll be addressing.

**Comment by philiparthurmoore** [comment]
PHP was super-easy. My hope is that the JS will be easy also. Most of these issues look very minor.

**Comment by iamtakashi** [comment]
I'd suggest to make a PR for each JS file. That would be easier to test.

**Comment by ihorvorotnov** [comment]
@iamtakashi I'm fetching latest code right now to fix that js stuff. Separate PR for every file is an overkill, I'm going to push a separate commit for every file, it should be enough as all the errors are just coding standards - extra spacing, missing dots etc (it's unlikely going to break smth). If you really need it to be a PR per file - please let me know.

**Comment by iamtakashi** [comment]
ok, one PR is fine.

**Comment by ihorvorotnov** [comment]
I'm afraid the js part is a bit trickier then I thought. I've fixed all minor issues, PR is coming soon. However, there are some pieces I would like to discuss with you guys. I'll post here a detailed log with my comments after the PR.

**Comment by ihorvorotnov** [comment]
So, there's #152 that fixes all minor issues. Let's walk through Travis logs and see what left (and why):

#### /js/color-scheme-control.js

**All identifiers must be camelCase or UPPER_CASE**:
https://travis-ci.org/WordPress/twentysixteen/jobs/79746211#L218
https://travis-ci.org/WordPress/twentysixteen/jobs/79746211#L226

It's about renaming variables, and it's not about just renaming them on this lines, obviously. I didn't touch this because I don't know, maybe there's a reason for this names and because I'd suggest the author of this script will do a better job. Besides, I'm just starting with Customizer, so I kinda suck in this area :) and don't want to risk to introduce new bugs instead of fixing.

#### /js/functions.js

**Not yoda condition**:
https://travis-ci.org/WordPress/twentysixteen/jobs/79746211#L234
https://travis-ci.org/WordPress/twentysixteen/jobs/79746211#L242

However, in this cases both yoda conditions are in ternary operator with false-true-false pattern, which, from my experience becomes harder to grasp if it's yoda-style, e.g.:

```
_this.attr( 'aria-expanded' ) === 'false' ? 'true' : 'false' // current non-yoda style
'false' === _this.attr( 'aria-expanded' ) ? 'true' : 'false' // yoda style applied
```

Would like to hear your opinions on this.

**Variable declarations must be the first statements of a function scope**:
https://travis-ci.org/WordPress/twentysixteen/jobs/79746211#L250

Well, before the first variable we have an IF statement that runs a check and exits function if condition is met. This check is on its place, I don't see a reason to define a variable before the check. However, it's a single local var, so no performance / memory problem here. Maybe we just force jscs to ignore this line?

#### /js/skip-link-focus-fix.js

**All identifiers must be camelCase or UPPER_CASE**
https://travis-ci.org/WordPress/twentysixteen/jobs/79746211#L258
https://travis-ci.org/WordPress/twentysixteen/jobs/79746211#L266
https://travis-ci.org/WordPress/twentysixteen/jobs/79746211#L274
https://travis-ci.org/WordPress/twentysixteen/jobs/79746211#L282
https://travis-ci.org/WordPress/twentysixteen/jobs/79746211#L290
https://travis-ci.org/WordPress/twentysixteen/jobs/79746211#L298

All mentioned vars are `is_ie`, `is_opera`, `is_webkit` etc - pretty familiar naming convention for conditional checks. Not sure if it needs to be changed just to fit the rule "camelcase var names in js". What do you think?

I decided to push a PR with those minor changes first, so it can be merged asap reducing the number of errors in failed checks then discuss the rest with you.

**Comment by ntwb** [comment]
JavaScript isn't my thing but the WordPress Coding Standards for JavaScript are here:
• https://make.wordpress.org/core/handbook/best-practices/coding-standards/javascript/

Following these as closely as possible is the ideal scenario, this page also hasn't had any updates (apart from stylistic tweaks) in ~2 years so if something isn't there that should be, or if something needs clarification we can probably wrangle some #core devs to chime in here to help out if needed.

**Comment by philiparthurmoore** [comment]
@ihorvorotnov I consider most of these very trivial matters. Happy to put together a pull request today that addresses most, if not all, of the questions you've asked above.

**Comment by ihorvorotnov** [comment]
@philiparthurmoore I'll be busy today, go for it. Thank you!

**Comment by philiparthurmoore** [comment]
Sounds good. I'll put something together before I head out for the day. Cheers.

**Comment by ihorvorotnov** [comment]
We did it, Travis CI smiles in green now :) Thanks to everyone who made it happen!
This issue may be closed, I think. And `needs patch` should be removed as well.
