### ISSUE TITLE
Device testing

### ISSUE THREAD

**Issue by karmatosed** [WordPress/twentysixteen#175]
As with any theme it's great to test in a variety of devices. This issue is an attempt to get this organised. I'm going to list a range of devices we should at minimum test in. 

Here is a suggested list of devices we need covered:
- Android phones : pick your favourite (Nexus etc)
- iPhone: 5, 6, 6 plus
- iPad : mini retina, retina, non-retina
- Android tablets
- Anything else you choose to test on

A little extra credit note. It would be great to really put this through the edge cases ( Sony Vita.. whose got an old Blackberry :) ). Our goal isn't to support every old device, but it would be great to at least know the limits. If you can think of one then follow the reporting format and lets see those edges!
## Reporting format

As you test if you can state the device used as a comment on this issue. This lets us keep a record and can then be something . It can then be crossed off. As an extra thing it could be fun to get a screenshot of each device. You don't have to, but this would be great.
## Reporting an issue

If you actually find a bug when testing with devices, please open a new issue per bug. When you do please show a screenshot and let us know what the device was you tested on. If applicable the resolution too.

A useful post on testing is here: https://make.wordpress.org/core/2015/03/16/mobile-patch-testing-with-vvv-and-xip-io/. I personally use Charles Proxy and it works really well with vagrant: http://www.charlesproxy.com/

**Comment by karmatosed** [comment]
Tested: iPhone 6 iOS9, iOS8 - landscape and portrait
1 bug filed.

**Comment by karmatosed** [comment]
Tested: [browserstack] Windows Phone Nokia Lumia 930 8.1

![bs_winphone_mobile_nokia lumia 930-8 1-1080x1920](https://cloud.githubusercontent.com/assets/253067/9941033/bcb52992-5d6a-11e5-9aab-17d9054bc018.jpg)

**Comment by karmatosed** [comment]
Tested: iPad Mini Retina iOS8 - landscape and portrait.

**Comment by ehti** [comment]
Tested: HTC One XL, Android 4.2.2, Sense 5.0 using HTC Browser. Portrait and landscape.

Unexpected menu button position? Rest of the behavior was fine. Also, menu button position was the expected top-right when using Chrome on this same phone.

![image](https://cloud.githubusercontent.com/assets/6505293/9976916/71fe9434-5f0d-11e5-9aec-0b01efb59192.png)

![image](https://cloud.githubusercontent.com/assets/6505293/9976922/bdf07f60-5f0d-11e5-9f05-32f31d2d9177.png)

**Comment by iamtakashi** [comment]
The above, I assume the HTC browser doesn't support the flex box or needs the old syntax. However, I don't think this is a big deal for this browser as long as tapping the button displays the menu.

**Comment by ehti** [comment]
Indeed, the menu is displayed just fine on tapping.

**Comment by iamtakashi** [comment]
Ok, cool. Thanks for testing!
