### ISSUE TITLE
Browser testing

### ISSUE THREAD

**Issue by karmatosed** [WordPress/twentysixteen#176]
As with all good things, it's time to really put Twenty Sixteen through its browser paces.

As a minimum we should be testing:

IE: 7 should not crash, 8 should be legiable, rest should work
Firefox
Chrome
Safari
Opera

We should also be testing across platforms on both Max, Linux and Windows. Also a range of versions for those too would be good to be fully sure.
## Reporting format

As you test if you can state the browser you used as a comment on this issue. This lets us keep a record and can then be something . It can then be crossed off. As an extra thing it could be fun to get a screenshot of each browser. You don't have to, but this would be great.
## Reporting an issue

If you actually find a bug when testing with browsers, please open a new issue per bug. When you do please show a screenshot and let us know what the browser was you tested on. If applicable the resolution too and device.

Now go test and really put Twenty Sixteen through it's paces!

**Comment by iamtakashi** [comment]
Just to note, as #6, CSS for IE8 and 7 haven't been worked on yet.

**Comment by karmatosed** [comment]
Tested: [browserstack] Windows Edge

![bs_win10_edge_20 0](https://cloud.githubusercontent.com/assets/253067/9941209/aeb9cda6-5d6b-11e5-84e1-5560634a2ddb.jpg)

**Comment by karmatosed** [comment]
Tested: [browserstack] Windows IE 11

1 bug found and reported.

![bs_win10_ie_11 0 1](https://cloud.githubusercontent.com/assets/253067/9941371/cee73dec-5d6c-11e5-8916-40cc043aad16.jpg)

**Comment by karmatosed** [comment]
Tested: [browserstack] Windows Opera 31
![bs_win10_opera_31 0](https://cloud.githubusercontent.com/assets/253067/9941512/bbe057f0-5d6d-11e5-9237-d86faab218fe.jpg)

**Comment by karmatosed** [comment]
Tested: Safari Mac

**Comment by karmatosed** [comment]
Tested: Chrome Mac

**Comment by karmatosed** [comment]
Tested: Opera Mac

**Comment by karmatosed** [comment]
Tested: Firefox Mac

**Comment by karmatosed** [comment]
Tested: iPad Mini Retina
