### ISSUE TITLE
Possibly incorrect padding at intermediate screen widths

### ISSUE THREAD

**Issue by MickeyKay** [WordPress/twentysixteen#179]
Between screen widths of `44.375em` and `56.875em`, there is asymmetric whitespace to the left and right of the main content and title. 

![image](https://cloud.githubusercontent.com/assets/3189678/9869974/02f6e31c-5b3d-11e5-8ff4-6a4e35d7f426.png)

Not sure if there's a reason for this (e.g. does anything pull right at this width?), but it seems odd to have that wide strip of white on the right, but not on the left. Additionally, it seems like this whitespace is symmetric at all other screen widths:

**Comment by karmatosed** [comment]
I also see this, but it may be part of the intended design. Lets flag for design review.

**Comment by SeanChDavis** [comment]
This was intentional. It's for readability. See: https://github.com/WordPress/twentysixteen/issues/104

**Comment by iamtakashi** [comment]
Yes. @SDavisMedia is correct — it's for readability. The idea is to make sure the character per line won't exceed roughly 70 to 75 which is traditionally considered as a good number.

I have considered to make it centred but I've decided to keep it left aligned to keep the relationship stronger with the header and the footer.

**Comment by MickeyKay** [comment]
Awesome! Glad to know you considered this.

**Comment by MickeyKay** [comment]
Awesome. Glad to know you considered this and made an informed (and
fantastic) decision :)
