### ISSUE TITLE
Top level menu items with children require double tap to access

### ISSUE THREAD

**Issue by tywayne** [WordPress/twentysixteen#183]
**Device details:**
iPhone 6
iOS 8.4.1
Safari

**Steps to recreate:**
1. Create a menu that has both items with and without children
2. Assign to 'Primary Menu' location
3. Tap a menu item with no children - this should result in navigating to the tapped item
4. Tap a menu item _with_ children - this will not navigate to that item
5. Tap the same menu item again - this will navigate to the item

Should be noted that this double-tap requirement is not apparent in the footer menu. Top level items with children are accessible with only one tap there.

**Comment by iamtakashi** [comment]
Good catch! The fix for dropdown menu on touch screens should run when screen is bigger than 910px wide.

**Comment by tywayne** [comment]
In looking into a fix for this, I found a section of `js/functions.js` that seems unnecessary, and when removed, resolves the issue. The section in question is [Lines 79-89](https://github.com/WordPress/twentysixteen/blob/master/js/functions.js#L79-89).

The containing anonymous function seems to be addressing an issue of accessibility of submenu items, and toggling a `.focus` class on focus/blur so that submenu items can be accessed with a keyboard.

Lines 79-89 are attempting to mimic the same action on touchscreen devices, but because of the `e.preventDefault()`, we're seeing the need for a double tap to access the link on touch screens.

I have a PR ready to submit that simply removes this section, because it doesn't seem necessary to add the `.focus` class for touch screens, but thought maybe there is some reason for that section that I'm just missing. Any thoughts @iamtakashi ?

**Comment by iamtakashi** [comment]
The function you are referring to is to fix the issue that is submenu items in the normal, non-mobile  dropdown inaccessible on touch devices. The normal non-mobile navigation appears on, for example, iPad landscape orientation.

So, we definitely want to keep that but like I said before we just need to make it run for the screen bigger than 910px wide.

**Comment by iamtakashi** [comment]
Reference: https://core.trac.wordpress.org/ticket/24767
