### ISSUE TITLE
'Continue reading %s' string needs a translator comment, not a context

### ISSUE THREAD

**Issue by SergeyBiryukov** [WordPress/twentysixteen#186]
In 999132e for #25, the translator comment for `'Continue reading %s'` was replaced with a context.

The translator comment was appropriate there, no need to move it to context:
- Translator comments are meant to explain the usage of placeholders in a string.
- `_x()` is meant to distinguish the same string used in different contexts.

Now we have two duplicate strings, [one with](https://github.com/WordPress/twentysixteen/blob/master/inc/template-tags.php#L184) and [one without](https://github.com/WordPress/twentysixteen/blob/master/template-parts/content.php#L32) context, though both are used in exactly the same context.

See also three instances of the same string in Twenty Fifteen, all of which are correct ([inc/template-tags.php](https://core.trac.wordpress.org/browser/tags/4.3.1/src/wp-content/themes/twentyfifteen/inc/template-tags.php#L237), [content-link.php](https://core.trac.wordpress.org/browser/tags/4.3.1/src/wp-content/themes/twentyfifteen/content-link.php#L29), [content.php](https://core.trac.wordpress.org/browser/tags/4.3.1/src/wp-content/themes/twentyfifteen/content.php#L31)).

999132e should be reverted.

**Comment by karmatosed** [comment]
We have a review ticket, so for now I'm merging this into that.

**Comment by SergeyBiryukov** [comment]
@karmatosed This has nothing to do with escaping though, but rather with i18n best practices.

**Comment by karmatosed** [comment]
I think it comes under that, but we can discuss seperately. Re-opened to do that.

**Comment by iamtakashi** [comment]
This is nothing to do with escaping. The PR from Sergey makes sense to merge. So that we don't have duplicated strings with a same context.

**Comment by karmatosed** [comment]
I was more thinking to put all together, but totally fine. I'll merge this now.
