### ISSUE TITLE
Php notice when updating twenty sixteen used as parent

### ISSUE THREAD

**Issue by dev-xiligroup** [WordPress/twentysixteen#188]
When updating twenty sixteen used as parent in themes page:

PHP Notice:  Undefined index: preview in /Applications/MAMP/htdocs/wp_svn43/wp-admin/includes/class-wp-upgrader-skins.php on line 742

**Comment by karmatosed** [comment]
I just tested this and don't get this issue. I would suggest you make sure no plugins are activated. If you still get this, please add a comment with exact steps.

I am for now closing as unable to replicate.

**Comment by dev-xiligroup** [comment]
After some research, it is due an unwanted concatenation =  ticket https://core.trac.wordpress.org/attachment/ticket/33427/33427.diff 
but not yet fixed in WP 4.3.1
Cheers
