### ISSUE TITLE
Escaping review

### ISSUE THREAD

**Issue by karmatosed** [WordPress/twentysixteen#190]
There is a fair bit of to and fro about escaping and when too much is going on (or not enough). As we talked about in this weekly meeting, lets now bring that here to give everyone a chance to suggest a way through this. In the past, when a default theme goes into core it has had a ticket removing a lot of work done because of over escaping. Lets try and minimise that this time and find a way to make this work from now on.

Pinging a few people to get the conversation rolling: @fklein-lu @dd32 @ocean90

**Comment by ocean90** [comment]
I did a review of the theme without looking at Dion's PR first and they look pretty similar: https://github.com/ocean90/twentysixteen/commit/347dc701f18ca63b8fd86b014e8b50a3a172e46a

Only https://github.com/dd32/twentysixteen/commit/1fb2fd014f165acd7a9418cb1fb22c3f48a44a66 is missing.

**Comment by karmatosed** [comment]
~~Noting that: https://github.com/WordPress/twentysixteen/issues/186 relates. Edit: clarifying by relates, it kind of does as we're batch updating things done and this was done in same pass.~~

Edit: that issue has been merged.
