### ISSUE TITLE
Some yoda conditions in functions.js are difficult to read.

### ISSUE THREAD

**Issue by tywayne** [WordPress/twentysixteen#195]
When comparing to an integer using `<, >, <=, >=`, the use of a yoda condition makes it difficult to understand.

[Example - L98 in functions.js:](https://github.com/WordPress/twentysixteen/blob/master/js/functions.js#L98) 
`if ( 910 > window.innerWidth )` is doing something when the window is smaller than 910, which would be much more readable as `if ( window.innerWidth < 910 )`

This is outlined in the [coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#yoda-conditions): 
`Yoda conditions for <, >, <= or >= are significantly more difficult to read and are best avoided.`

**Comment by karmatosed** [comment]
Do you have a patch for how to do this better?

**Comment by karmatosed** [comment]
Awesome, thanks for this.
