### ISSUE TITLE
Include Content Bottom Sidebar on 404.php

### ISSUE THREAD

**Issue by eduardozulian** [WordPress/twentysixteen#200]
On an instalation without any widgets added to the main sidebar, this is how `404.php` looks like:

![captura de tela 2015-09-16 as 22 33 22](https://cloud.githubusercontent.com/assets/1136160/9922894/69e69c92-5cc4-11e5-8cbb-8d0dfa4fc272.png)

It's not bad at all. However, by introducing the `content-bottom` sidebar, we could have a more helpful `404.php`:

![captura de tela 2015-09-16 as 22 41 13](https://cloud.githubusercontent.com/assets/1136160/9922895/69e8a69a-5cc4-11e5-933a-c627542c1269.png)

A pull request is on its way. :smile:

**Comment by karmatosed** [comment]
I'm going to flag for design review, but I'm not personally super keen we add a new sidebar in. I think having a minimal 404 page isn't a bad thing.

**Comment by eduardozulian** [comment]
I don't think it's bad either, @karmatosed.

Maybe I was misunderstood, but it's not a new sidebar rather than the one that can be presented on post and pages. Hence, since both widget areas (_Content Bottom 1_ and _2_) are optional, we are still leaving this – the ability to provide some helpful content about the website – up to the user.

Thank you!

**Comment by iamtakashi** [comment]
I actually like this idea. We already have the widget areas and I can see it can be helpful for the page with just one line addition to the template.

**Comment by karmatosed** [comment]
Ok, cool let me merge it then. Thanks for the idea @eduardozulian

**Comment by eduardozulian** [comment]
Glad I can help. :smile: 

Thanks, @karmatosed and @iamtakashi.
