### ISSUE TITLE
Long non-breaking categories cause visual issue.

### ISSUE THREAD

**Issue by karmatosed** [WordPress/twentysixteen#204]
When using Safari I see the following:

![img_0201](https://cloud.githubusercontent.com/assets/253067/9940246/9387990a-5d66-11e5-84c1-1fbdee0eb25c.PNG)

**Comment by karmatosed** [comment]
If anyone could give me a sanity check on this it would be great. Trying to work out if an issue on all for iOS9.

**Comment by karmatosed** [comment]
Updating title and addding reason of long categories:

![file 17-09-2015 18 18 42](https://cloud.githubusercontent.com/assets/253067/9940586/ad66c380-5d68-11e5-800a-860d3ba4bc4c.png)

**Comment by LateButEarly** [comment]
This seems to be related to this bug. I believe I have a fix, but haven't contributed to a theme before, so please let me know if this is in the wrong place. A possible solution is underneath the bug confirmation.

![long_category_twentysixteen](https://cloud.githubusercontent.com/assets/6570433/9951866/b36b08c2-5d9a-11e5-9e27-f28041834540.png)

Possible solution:

![fix_long_category_names_twentysixteen](https://cloud.githubusercontent.com/assets/6570433/9951883/16d8f11c-5d9b-11e5-9485-e2a60be6e71b.png)

Tested on mobile:

![fix_long_category_names_mobile_twentysixteen](https://cloud.githubusercontent.com/assets/6570433/9951907/5ac95768-5d9b-11e5-80a3-e3c8987cc8fd.png)

**Comment by maharzan** [comment]
Isn't this an edge case? What are some more realistic category/tag names?

**Comment by SeanChDavis** [comment]
@maharzan I don't think it would be an edge case for everyone. Check out the discussion that broke out on my now merged and closed PR/issue. #34

**Comment by maharzan** [comment]
Okay.. I thought they were regarded as edge cases when a similar case was raised for titles..

**Comment by iamtakashi** [comment]
I'll add the `word-break` _a little_ more universally with the PR above. I think it's pretty safe because many of elements already had the rule. Let's see if it will cause any issues.

**Comment by LateButEarly** [comment]
Sounds good @iamtakashi
