### ISSUE TITLE
IE11 menus and scrollbars

### ISSUE THREAD

**Issue by karmatosed** [WordPress/twentysixteen#205]
In most browsers no extra scrollbars appear on going to the sub menus. However, on IE 11 they appear both horizontally and vertically. This may be something we accept as IE behaviour, however flagging as doing browser testing and it's specific behaviour to IE.

To replicate, just view in IE11 and go to sub menus as shown in screenshot. My screen was a Macbook 13 using Browserstack.

![bs_win10_ie_11 0](https://cloud.githubusercontent.com/assets/253067/9941294/3a6e2b76-5d6c-11e5-9dd5-445f72c6b2de.jpg)

**Comment by iamtakashi** [comment]
We've talked about this in #112 and #123. And we agreed as a design limitation.

**Comment by karmatosed** [comment]
Ok, noting for records this is also in Opera incase it's reported later.

**Comment by iamtakashi** [comment]
It will happen on any browser.
