### ISSUE TITLE
Inconsistent use of $ to designate a jQuery object in variable name

### ISSUE THREAD

**Issue by tywayne** [WordPress/twentysixteen#214]
While I do not believe it is listed in any official capacity as a coding standard, it is common to prefix a variable name with `$` to designate it as a jQuery object. This is currently used inconsistently.

Example in [L9 of functions.js](https://github.com/WordPress/twentysixteen/blob/master/js/functions.js#L9) shows the use of `$body`, but no prefix on `masthead` (and others). 

We should either use the `$` across the board, or not at all, to avoid confusion. My vote would be to use it, as it is handy to know at a glance which variables are jQuery objects.

**Comment by tywayne** [comment]
Meeting discussion - https://wordpress.slack.com/archives/core-themes/p1442592104000766

Also related - https://wordpress.slack.com/archives/core/p1441922197000839

**Comment by karmatosed** [comment]
We decided in meeting to go with having none to be consistent. We could do with a patch for this as a result.
