### ISSUE TITLE
Author Title in Biography Should be h2

### ISSUE THREAD

**Issue by iamtakashi** [WordPress/twentysixteen#219]
It's currently `h3` and if we check document outline, it reports we have a missing heading.

![screen shot 2015-09-19 at 19 30 17](https://cloud.githubusercontent.com/assets/908665/9977592/9f52702a-5f05-11e5-923f-8be981fd4d06.png)

With `h2`:
![screen shot 2015-09-19 at 19 26 28](https://cloud.githubusercontent.com/assets/908665/9977594/b23683c0-5f05-11e5-9d67-48cdf53eeaf7.png)

**Comment by karmatosed** [comment]
Merged to fix.
