### ISSUE TITLE
San Francisco font for iOS and OS X

### ISSUE THREAD

**Issue by ihorvorotnov** [WordPress/twentysixteen#233]
We have Helvetica Neue as a fallback font for Montserrat on iOS / OS X. However, since iOS 9 and OS X El Capitan, watchOS 2, and tvOS [Apple switched to its new system font San Francisco](https://developer.apple.com/fonts/). Twentysixteen is going to be used in 2016, should we consider  replacing Helvetica Neue with San Francisco? Or adding San Francisco before Helvetica Neue.

What do you think? Let's discuss it.

**Comment by karmatosed** [comment]
I personally don't think so, but lets get @iamtakashi to give a design view on this. To me, that doesn't mean we should default to using San Francisco on iOS devices.

**Comment by ihorvorotnov** [comment]
Anyway, we're talking about fallback font. The main font is Montserrat, so it's not really a big issue, at all. I've had a chance to work with SF font today, and found it awesome and way better than Helvetica (which is actually one of my favorites for almost two decades). What I find interesting - SF has Display and Text variants served dynamically, one of them is optimized for small font size - it's actually where Helvetica Neue fails all the time. According to specs, small size is <= 20px

**Comment by karmatosed** [comment]
It absolutely is a great font. I think for me, fallbacks are nice as being uniform not platform specific. However, lets get design feedback on this.

**Comment by iamtakashi** [comment]
The choice of Helvetica Neue was a progressive enhancement and if we're taking this further we could _replace_ the fallback to San Francisco because it'll be the default system font from OS X El Capitan.

So like... `font-family: Montserrat, "San Francisco", sans-serif;` ?

In the case where Montserrat is disabled then, new Mac will use San Francisco, old Mac use Helvetica, and Windows use Arial.

What do you think?

**Comment by ihorvorotnov** [comment]
> fallbacks are nice as being uniform not platform specific

In this case both Helvetica and San Francisco are bad choices, because they are standard for Apple's OSes. There's no Helvetica / Helvetica Neue on Windows at all, and, AFAIK, on Ubuntu, Mint and some other Linux systems :)

**Comment by ihorvorotnov** [comment]
> In the case where Montserrat is disabled then, new Mac will use San Francisco, old Mac use Helvetica, and Windows use Arial.

That's exactly what I thought of when started this issue. In this case we have the best fallback coverage in case Montserrat is missing (or missing subset - cyrillic, vietnamese etc).

P.S.: and not only new Macs will use SF, all iPhones and iPads upgraded to iOS 9.

**Comment by karmatosed** [comment]
Noting that whatever we decided needs a lot of testing. It's to me a little late for little gain. It needs properly restesting on all devices if this is the case and it's done. That's an undertaking.

**Comment by ihorvorotnov** [comment]
@karmatosed I'm sure there's no need for any additional testing. It will only force iOS 9 (millions of  iPhones and iPads in 2016) and El Capitan to use San Francisco and its design is very close to Helvetica, so no additional spacing / sizing issues here. If SF is not available, it will default to system sans-serif, which is Helvetica Neue / Helvetica for older Apple platforms, Arial for Windows, Ubuntu for Ubuntu etc. 

And the whole issue is with fallback font, not the main typeface. However, imo, it's not the edge case 'cause we'll have a lot of iOS9 users in 2016.

**Comment by karmatosed** [comment]
We should test everything :)

**Comment by ihorvorotnov** [comment]
Agree :+1:

**Comment by iamtakashi** [comment]
As we discussed in <a href="https://wordpress.slack.com/archives/core-themes/p1443199122001159">#core-themes</a> today, it is nice to have but just is too close to the merge and we don't have enough time to test. So, we've decided to leave as it is.

Thanks for the suggestion anyway.

**Comment by ihorvorotnov** [comment]
Makes sense. Feel free to add it later or ping me when you're ready, I'll send a PR.
