### ISSUE TITLE
Accessibility: disambiguate landmarks with same role

### ISSUE THREAD

**Issue by afercia** [WordPress/twentysixteen#236]
When navigational landmarks have the same role, for example "navigation", they'd need a label to disambiguate them. See for example what was done in core, where the admin screens have two `role="navigation"` and they have different `aria-labels`: "Main menu" and "Toolbar".
Not sure this should be done for all the complementary roles too, but I'd recommend it for navigation.

**Comment by davidakennedy** [comment]
I agree with this, so I made a pull request. :smile: This is something we encourage in the accessibility-ready requirements, but I missed it during my initial review. This is a good way to make the menus more specific and useful for users with assistive technology.

Like I mention in my PR, we may want to change the wording.
