### ISSUE TITLE
Should the white background be limited to 1200px or so?

### ISSUE THREAD

**Issue by maharzan** [WordPress/twentysixteen#250]
On big screens, the white background extends to full width with the black background (which acts like border). Since we can use background images but this full stretch doesn't allow the site to show the background image if you want to use it. Maybe limiting the white background to 1200px or some number and centering that background along with the content might help those people who want to show the background image on larger screens. For me, it doesn't look nice with that huge white spaces on the sides.

**Comment by iamtakashi** [comment]
Thanks for your suggestion but my vision with the background is that it works like a thick border. This is a design decision since the beginning and I'm not going to change it from now.
