### ISSUE TITLE
offsetLeft() in functions.js is not called correctly on window resize

### ISSUE THREAD

**Issue by tywayne** [WordPress/twentysixteen#257]
Looks like this may have just been overlooked in #153. This function was reworked to process both images and blockquotes, and now requires a `param` argument to really do anything. 

When `offsetLeft` is called on window resize [here](https://github.com/WordPress/twentysixteen/blob/master/js/functions.js#L193), it isn't passed any arguments, thus isn't doing anything.

**Comment by iamtakashi** [comment]
Good catch! Thanks for spotting it.
