### ISSUE TITLE
screen-reader-text edit span visible

### ISSUE THREAD

**Issue by brentlogan** [WordPress/twentysixteen#259]
I now see the screen reader text after the edit link for a post or page, as shown below.

![bug](https://cloud.githubusercontent.com/assets/14060692/10034982/7b6ad7fa-614a-11e5-833c-f939480fb97b.png)

**Comment by kraftbj** [comment]
Caused by https://core.trac.wordpress.org/changeset/34444 . The text is now escaped with `esc_html`, which replaces the `<`, `>`, etc with the html entities.

**Comment by staylor** [comment]
I can revert those `esc_html()` calls

**Comment by staylor** [comment]
Reverted. Sorry. https://core.trac.wordpress.org/changeset/34452
