### ISSUE TITLE
Recent Posts widget with post date gap issue

### ISSUE THREAD

**Issue by maharzan** [WordPress/twentysixteen#26]
When there is Post Date in Recent Posts widget the gap between the title and date is larger than the gap between the list items.

Here is what is happening (first image) and how it should be (second image)

![recent-posts](https://cloud.githubusercontent.com/assets/883993/9562706/c0e46cc0-4e93-11e5-96a4-18225b98cdd6.png)

**Comment by iamtakashi** [comment]
Thanks for the report and the PR but I'm not crazy about the possibly randomly picked the value `1em`. Also it's best to apply the new style to the date in RSS widget also. I'll add a new PR here.

**Comment by maharzan** [comment]
How do you come with those numbers?

**Comment by iamtakashi** [comment]
The unit of the baseline grid is 7px in this theme.

**Comment by maharzan** [comment]
Thanks.
