### ISSUE TITLE
Genericons update to 3.4

### ISSUE THREAD

**Issue by samikeijonen** [WordPress/twentysixteen#267]
Genericons latest version is now 3.4. I believe that there is version 3.3 in the theme.

**Comment by karmatosed** [comment]
Sounds like a great idea. Could you work up a PR for us?

**Comment by samikeijonen** [comment]
Seem like this is already done in commit 4de01d829c91f837ec20ddc279db73708a7acacc.

**Comment by iamtakashi** [comment]
The version number in functions.php also needs to be changed. https://github.com/WordPress/twentysixteen/blob/master/functions.php#L224

**Comment by samikeijonen** [comment]
Sure. @maharzan can you do that in the same PR.

**Comment by maharzan** [comment]
Sure. @samikeijonen. Just doing that now.. Sorry I didn't see that part.

**Comment by maharzan** [comment]
Done. https://github.com/WordPress/twentysixteen/pull/274
