### ISSUE TITLE
Background for `ins` tag to light in dark colour scheme

### ISSUE THREAD

**Issue by grappler** [WordPress/twentysixteen#269]
When a text is wrapped in the `ins` tag the background is too light in the dark colour scheme.

![image](https://cloud.githubusercontent.com/assets/1785641/10054777/2ea1af5e-6233-11e5-9826-2ffe3eb16f5d.png)

See line 446 in the style.css

**Comment by karmatosed** [comment]
@iamtakashi what do you think? I think it's a valid suggestion.

**Comment by iamtakashi** [comment]
Yes. We should alter the the default style for the inserted text so that we don't need to introduce a new color. I'll think about it.

**Comment by iamtakashi** [comment]
With the PR:
![screen shot 2015-09-24 at 02 02 41](https://cloud.githubusercontent.com/assets/908665/10063011/d3575a12-6260-11e5-8c97-3b55d25b1339.png)

It also stays visible on other color schemes.
