### ISSUE TITLE
Accessibility: Low Color Contrast for the border or background colors

### ISSUE THREAD

**Issue by davidakennedy** [WordPress/twentysixteen#276]
The border color on input fields has low contrast. The color contrast for the border or background colors could be increased.

The border color `#e8e8e8` combined with the background-color `#f7f7f7` makes it hard to distinguish between the field and the background of the site `#ffffff`. The contrast for each of those is  1.23:1 and 1.07:1. This is less problematic with the comment fields because those have visible labels. But is more of an issue with the search form because its label is hidden by default.

Brought up in #253. Something I missed I my original testing. :disappointed: 

We should brainstorm about ways to make this better and keep the spirit of the design in tact.

**Comment by iamtakashi** [comment]
Search has the placeholder as clearly visible as a label though.

**Comment by iamtakashi** [comment]
We discussed in [#core-themes](https://wordpress.slack.com/archives/core-themes/p1443197846001095) today. I'm going to make a patch with the suggestion.

> So maybe a good compromise is darkening the border slightly more than it is now, not to 4.5:1 and making placeholder be 4.5:1.

**Comment by iamtakashi** [comment]
I've increased the contrast for both secondary text color and border color.

Secondary text is now #686868 and the contrast ratio is the following.
4.55:1 — When it's used for placeholders on #e8e8e8
5.57:1 — When it's used for labels on #ffffff
