### ISSUE TITLE
Sub Menu bug

### ISSUE THREAD

**Issue by maharzan** [WordPress/twentysixteen#278]
I just found a menu issue.

On your desktop, if you click the small arrow on the menu item, it opens up the sub menu, but then if you hover to other menu item, it shows that menu item too. You have to click again to hide that earlier submenu. Here is a screenshot.

![menu](https://cloud.githubusercontent.com/assets/883993/10075153/f04215ac-62f3-11e5-8cd9-a754d8e201f2.png)

**Comment by iamtakashi** [comment]
I can't replicate this issue.

> if you click the small arrow on the menu item, it opens up the sub menu

I can't "click" the small arrow and it shouldn't let me. Are you sure you don't have any local modification on your copy?

**Comment by maharzan** [comment]
Hover over the menu with a mouse, it opens up the sub menu, then click on the small arrow. You will see the menu is now shown, if you move the mouse away, the menu still shows. Hover to another menu (with submenu) and there you have 2 submenus showing. The copy I have is latest.

**Comment by maharzan** [comment]
I am using Chrome on OSX Yesomite 10.10.1

**Comment by maharzan** [comment]
Interestingly, it doesn't seem to happen on Safari.

**Comment by iamtakashi** [comment]
That's really weird. I can't replicate. 

The arrow is a pseudo element in the menu item anchor, therefore when I click the arrow, I'm clicking the menu item and it takes me to the page.

It sounds like the submenu fix in `functions.js` is not working for you as expected. https://github.com/WordPress/twentysixteen/blob/master/js/functions.js#L73

But I'm not sure why. Let's hear if anyone can replicate the issue. I might be missing something.

**Comment by maharzan** [comment]
Ok I think I found what might be happening. Instead of a real page, I have a # menu link on the parent menu. Thats why its seems to be clickable. Can you try with that?

**Comment by iamtakashi** [comment]
Okay... then that's expected. I think it would happen in Twenty Fourteen and Thirteen.

I don't think this is a valid bug or an extreme edge case. (Why would you want to have a menu item with a hash?)

**Comment by philiparthurmoore** [comment]
> Why would you want to have a menu item with a hash?

Many, many reasons. I often do this when organizing menus or sites and the top-level menu item is something like Themes, Plugins, Categories, etc. Lots of use cases for having a hash menu link.

**Comment by maharzan** [comment]
Usually, when you don't want to redirect people to another page on the parent menu, people use #. This is especially valid on touch devices when you want to open a sub menu rather than go to a redirect loop and never open the sub menu. We have had that case by quite a number of users in our forums.

**Comment by iamtakashi** [comment]
> This is especially valid on touch devices when you want to open a sub menu rather than go to a redirect loop and never open the sub menu.

To me, that's a hideous hack for themes that don't bother to fix the issue on touch devices. I know WordPress.com suggests this as a workaround but if people care to fix themes users don't need do that kind of hack.

But this is not the case in this theme. That's why we have submenu fix on touch devices. Twenty Thirteen and Twelve have similar fix too.
https://github.com/WordPress/twentysixteen/blob/master/js/functions.js#L73

Since that's a "hack" and this theme does have a solution to invalidate the hack eve more, this is not a valid bug.
