### ISSUE TITLE
Insufficient check for existence of #menu-toggle in functions.js

### ISSUE THREAD

**Issue by tywayne** [WordPress/twentysixteen#294]
The `menuToggle` variable is set with `menuToggle = masthead.find( '#menu-toggle' );`
This will set `menuToggle` to a jQuery object whether the `#menu-toggle` element was found or not.

Later, this check is found: 

```
// Return early if menuToggle is missing.
if ( ! menuToggle ) {
    return;
}
```

This is meant to return early if `#menu-toggle` doesn't exist, but since `menuToggle` is an object, it is always truthy. We should be checking for `menuToggle.length`

**Comment by iamtakashi** [comment]
Good catch!
