### ISSUE TITLE
Make 4.2 as minimum version because of the use of wp_script_add_data()

### ISSUE THREAD

**Issue by iamtakashi** [WordPress/twentysixteen#3]

**Comment by karmatosed** [comment]
Closed in: https://github.com/WordPress/twentysixteen/commit/3f169ceaa802deac76a9be03e96a4c533e1e321e

**Comment by obenland** [comment]
This will probably be 4.4 at the end of it all. I'd like Twenty Sixteen to piggyback comment navigation template tags into core. I'm also pretty sure that there will be more things like that that will materialize during the release. Like that nasty search form callback for screen reader text.
