### ISSUE TITLE
Escaping Clarification Requested

### ISSUE THREAD

**Issue by philiparthurmoore** [WordPress/twentysixteen#300]
Asking again in its own Issue, since my questions in Slack and GitHub have largely gone unanswered: is there a discussion link that references why all the escaping in the theme was taken out? See also: https://wordpress.slack.com/archives/core-themes/p1443070214001020 and #240.

I am asking not to have escaping added back in, but to understand where I should be looking to for the correct rules and standards around escaping and theming. Rules between WordPress.com, WordPress.org, and the default themes do not seem consistent in this regard and I am quite confused if I can or cannot begin using Twenty Sixteen as a reference point to a theme that exhibits 100% best practices with regard to escaping and security.

Thanks.

**Comment by karmatosed** [comment]
You absolutely can use Twenty Sixteen. Just like any default theme. Historically default themes have actually had their escaping reversed in core. So, just like Twenties before this, we are simply doing it before. There is a lot of subjectivity over escaping. .com has traditionally done it a lot more, hence the discrepancy.

@ocean90 and others may care to add extra context, however as this isn't an issue with the code and I'm triaging, I am going to close this up for now.
