### ISSUE TITLE
Dropdown menus and touch not working as intended in Firefox

### ISSUE THREAD

**Issue by trenzterra** [WordPress/twentysixteen#301]
I run a tablet on Windows 8.1 (have not upgraded to Windows 10 due to some compatibility issues, but that's beside the point). 

In past WordPress themes (excluding TwentyFifteen where you had to click the arrow to dropdown), registering a hover action via touch has always been and issue for dropdown menus (i.e. menus with a child item inside), as the browser usually inteprets it as a click, and the dropdown menu does not appear.

In TwentySixteen, I'm glad this problem has been solved in both Chrome and Internet Explorer. When I first touch the menu item via my finger, it registers it as a hover and the dropdown menu opens. Only upon the second touch does the browser register it as a click.

However, in Mozilla Firefox (version 41), it still does not register as a hover on the first touch, but a click.

Thus, I was wondering if this can be fixed in TwentySixteen? I don't have an Android tablet to test so I'm not sure if it happens on Mozilla Firefox on an Android device as well.

**Comment by iamtakashi** [comment]
Tested on Firefox (v41) in Android tablet (Android 5.1.1). It works as expected — First tap on a menu that has child menu items opens submenu, and second tap takes to the page.

I don't own a Windows tablet. Can anyone else replicate the issue?

**Comment by trenzterra** [comment]
Hi Takashi,

I think it can be emulated by going into the F12 menu, clicking on Responsive Design, and then the 'Simulate Touch Events' button.

I'm just curious how Twentysixteen inteprets touch? Does it use pointer events or touch events, or both?

Many thanks!

**Comment by trenzterra** [comment]
Hi there, I just tested on the nightly version of Firefox (44) and it seems to work now. Seems like Firefox just added pointerevents support back in August and it's yet to make it to the stable builds.

However, I still notice one problem with Firefox and Chrome: while you can open the menu with a tap, you can't close it by tapping elsewhere; the child menu remains open. Is there a way to fix this?

**Comment by iamtakashi** [comment]
> I'm just curious how Twentysixteen inteprets touch? Does it use pointer events or touch events, or both?

Touch Events. See: https://github.com/WordPress/twentysixteen/blob/master/js/functions.js#L96

> you can't close it by tapping elsewhere; the child menu remains open. Is there a way to fix this?

I personally don't think that's a huge deal but it maybe nice to fix.

**Comment by karmatosed** [comment]
If we get a PR in today lets do that, otherwise lets close as we need to make sure we get ready for merge. @trenzterra if you want to do a PR today, please do.

**Comment by trenzterra** [comment]
I don't have much knowledge about JavaScript so I don't think I will be able to patch this. But I have a suggestion to make, if someone could implement this in time it would be great:

Since menus with child menus will have the dropdown arrow, why not design the dropdown arrow to become a toggle, a la twentyfifteen? The hover behaviour could remain unchanged. on non-touch devices. But on touch devices, tapping the main menu text on a touch device will bring you to the linked page, avoiding the need for a second tap and allows touch users to be aware that there is a link behind the main menu text and it is not a placeholder. Meanwhile, tapping on the arrow would trigger a toggle to expand/close the menu.

Any thoughts?

**Comment by trenzterra** [comment]
Implementing such a behaviour will also make for a consistent touch experience across tablets and smartphones, where the mobile menu already operates on a similar premise.

**Comment by iamtakashi** [comment]
> Meanwhile, tapping on the arrow would trigger a toggle to expand/close the menu.

The arrow has to be a lot bigger with your idea. (no one really can tap the tiny arrow in non-mobile menu). And having a huge arrow negatively impacts to the design a lot.

Like I said before, not letting people close dropdown is really not a big deal.

**Comment by karmatosed** [comment]
We talked about this in meeting and flagging as won't fix.
