### ISSUE TITLE
Inconsistent use of single vs double quotes for HTML attributes

### ISSUE THREAD

**Issue by tywayne** [WordPress/twentysixteen#302]
Noticed a couple uses of single quotes around an attribute value in `header.php` and `footer.php`, while we use doubles everywhere else.

Looks like they were added in [4d434f6](https://github.com/WordPress/twentysixteen/commit/4d434f612cd21887f879a6c8e82f152160ff975f) when adding the `aria-label` attributes to the `nav` elements. It shouldn't make a difference either way, but unless I'm missing a specific reason for them to be single quotes in those instances, we should use doubles for consistency.

**Comment by iamtakashi** [comment]
I think this has been just overlooked. Thanks for spotting it.
