### ISSUE TITLE
box-shadow vs. border-bottom for links

### ISSUE THREAD

**Issue by brentlogan** [WordPress/twentysixteen#304]
I'm curious about the decision to go with box-shadow instead of border-bottom for links. A bug in Windows Chrome results in a 1px vertical line on the left side of links some of the time (not all of the time). See screen capture below.

![bug](https://cloud.githubusercontent.com/assets/14060692/10126867/f2f0ab04-654d-11e5-95b1-5d2f8d867deb.png)

Potential work arounds are:

`box-shadow: 0 2px 0 -1px currentColor;`
`box-shadow: 0 -1px 0 0 currentColor inset;`
`border-bottom: 1px solid currentColor`

And yes, I understand this is an issue with Chrome, not Twenty Sixteen. It doesn't appear in Microsoft Edge or Firefox.

**Comment by iamtakashi** [comment]
The approach with box-shadow was to attempt not needing a transparent bottom border when we want to remove it on hover. Sometimes without the transparent border, the element jumps. See
- https://core.trac.wordpress.org/ticket/30654
- https://core.trac.wordpress.org/ticket/30332

The intermittent bug in Windows Chrome is certainly annoying.

**Comment by brentlogan** [comment]
Ah, that makes sense. Thanks!

**Comment by karmatosed** [comment]
As discussed in meeting, closing due to being a browser bug.
