### ISSUE TITLE
Child-child menu getting cut off

### ISSUE THREAD

**Issue by trenzterra** [WordPress/twentysixteen#310]
I notice that child-child menus will appear offscreen at resolutions from around 910px to about 1,600px because there simply isn't enough whitespace on the right. An example is shown below:

![cutoff](https://cloud.githubusercontent.com/assets/14861280/10168381/131376ac-66ff-11e5-803b-5a7d2c71a561.png)

While I appreciate that child-child menus may be an edge use case, it would still be good to have them appear correctly.

What I suggest is this:
- Add a media query for resolutions in which the full menu is shown to the point where there is no cutoff, to change 'left: 100%' to perhaps something like 'left: 20%; top: 50%' so that it provides some leeway for users on those screen resolutions (particularly tablets and 1366x768 laptops).

If this is okay I can submit a PR.

**Comment by karmatosed** [comment]
For now, we are not fixing this as a known issue but the solution doesn't provide a consistent UX. We can look perhaps during testing once in core. But, probably as agreed this will be a won't fix until release.
