### ISSUE TITLE
Blockquote alignment causes issues at the top of posts

### ISSUE THREAD

**Issue by mor10** [WordPress/twentysixteen#32]
On wide screens, when blockquotes at the top of a post are aligned left, they cover the entry-footer data:

![blockquote-alignment](https://cloud.githubusercontent.com/assets/1132200/9563395/314ba418-4e37-11e5-85de-611a268f9a43.PNG)

This is a standard issue with this type of layout and will likely affect the full-width image display as well.

**Comment by karpstrucking** [comment]
I wonder if this is intended to be some type of pullquote behaviour?

**Comment by mor10** [comment]
It is a pull quote, triggered by applying the `alignleft` class to the blockquote. It also works as intended. This overlap situation is caused by the way the page is marked up and the styles are applied: Both the entry-footer and the left-aligned blockquote are pulled out of the natural context of the page, and since they are not "aware" of each other due to this positioning, they overlap.

**Comment by karpstrucking** [comment]
got it. front-end is admittedly my weakness - I'm not thinking of any way to reliably address with CSS. I suppose we could compare `.offsetTop` of `blockquote` elements to `.offsetTop+.offsetHeight` of `.entry-footer` and remove the `.alignleft` class with JS, but that seems zealous

**Comment by mor10** [comment]
I've encountered this problem with other designs in the past. The only "clean" (read non-JS) version I've found so far is to use floats and clears in a non-positional way by embedding the `entry-footer` in the container with the `entry-content` and floating it naturally. 

The larger issue here is that this same problem will appear when the full-width image solution is added. It is a design vs. code realities problem with no simple fix.

**Comment by iamtakashi** [comment]
> The larger issue here is that this same problem will appear when the full-width image solution is added.

@mor10, have you managed to replicate this issue? The over-hanging image solution checks if the image position is below the bottom of post meta.

**Comment by mor10** [comment]
How do you trigger the full-width image display within post content? I
assume there's a class or something?

In medias res on my paranoid android

**Comment by iamtakashi** [comment]
@mor10, No custom class needed. Upload an image equal or wider than 840px wide image and add it to the content with full or large size. This should be documented but let's leave it as another issue.

**Comment by mor10** [comment]
@iamtakashi I see. This doesn't happen with the Theme Unit Test data, but if you add a new image, the wide function does kick in and works properly for full-width images.

Having glanced at the JS that makes this happen I'd assume a similar function (or possibly the same) could be used to avoid the blockquote alignment issue in this ticket.

**Comment by karmatosed** [comment]
Related to this is what I can see here:

<img width="1236" alt="2015-09-10 at 18 51" src="https://cloud.githubusercontent.com/assets/253067/9796257/1fe3641c-57ed-11e5-8460-bd3f10f513aa.png">

I think it could be expected that someone would do a quote at the beginning. 

To replicate:
- Create new post
- Add blockqute with alignleft class
- Add content after

**Comment by mor10** [comment]
Yes, that is exactly the same as the screengrab at the top of the issue.

**Comment by valendesigns** [comment]
Shouldn't the footer just clear the float?

**Comment by mor10** [comment]
@valendesigns The left-aligned blockquote is positioned using a negative margin so even if the entry clears, it still collides with the floated content.

**Comment by MickeyKay** [comment]
Hey all, chiming in with my two cents. . . 

You can clear the `.entry-footer` element, but then it won't float left of the main content as is intended in it's most basic behavior. As @mor10 mentions, this is a challenging and complex layout issue that has no simple solution as far as I know. The fact that JS is required to deal with full-width images at all feels a bit jenky to me as well, but I can live with it.

@iamtakashi Is the left-align pull-quote the only other situation in which you can foresee this being an issue. If so, then we can mimic the full-image JS check and only apply the negative left margin if it'll clear the entry-footer. Again, this feels doubly jenky to me, but it would solve the problem.

If there are other elements/layouts for which this issue might occur, than it seems like a more generalized solution is in order.

**Comment by MickeyKay** [comment]
Added PR which should solve this specifically for blockquotes. As mentioned, if there are other elements that are known to cause this issue, then a more general solution should be implemented.

**Comment by iamtakashi** [comment]
@MickeyKay The left-align pull-quote and the full-width image are the only elements move into the left margin. I think your PR will fix this particular issue but it could be more "DRY" if we combine the check with the one for full-width image like the PR from @maharzan. I'm curious why you took this approach. Is the any particular reason?

**Comment by MickeyKay** [comment]
Ah, I just didn't see that PR :)

**Comment by maharzan** [comment]
PR refreshed.
