### ISSUE TITLE
Horizontal scroll with dropdown

### ISSUE THREAD

**Issue by krogsgard** [WordPress/twentysixteen#321]
I have a dropdown on the right most item and it causes horizontal scroll currently.

https://cldup.com/Y9pyWXHmjg.png

**Comment by iamtakashi** [comment]
This has come up before but we've "won't fixed" as a design limitation of the menu. 

A number of solutions have been suggested but all of them were inelegant or something like the cures being worse than the disease. The scrollbar only appears when you see the child menu items anyway and without it, the item won't be accessible.

I'm closing this as won't fix for now but this is something we can continue to think about. If you have a great flexible idea, please do let us know.

**Comment by krogsgard** [comment]
This is a very common thing... to put dropdowns on the last menu item. In my opinion a better design patter is to right align submenus if the menu is right aligned. I do this and have always done this wherever possible, to avoid this very issue. I don't think not handling the issue is a great fix. At a minimum I'd set a rule to right align the last menu item, even if it is painful to see as a designer :) Horizontal scroll is more painful.

**Comment by iamtakashi** [comment]
Thanks for your opinion, @krogsgard. As you can imagine, your solution has been considered but it's not simple when we need to accommodate with unknown number of menu items. The last item can easily at the left edge and we have the same issue.

![screen shot 2015-10-01 at 17 00 46](https://cloud.githubusercontent.com/assets/908665/10226200/07498e96-685e-11e5-86a8-7372c1c5b9fd.png)

**Comment by iamtakashi** [comment]
Just to be clear, we're not trying to not handle the issue. We haven't yet come across a great fix.

**Comment by krogsgard** [comment]
I understand. I just try to approach issues in terms of likely scenarios and unlikely scenarios.  A dropdown on the last menu item seems a more likely scenario than a relatively unattractive menu setup where it's overloaded. So yes, you may have the same issue, but if you fix it in the more likely scenario, you still have a fix for the majority of situations, versus no fix.

I'm sure you've hashed it out before. Feel free to not do anything. Just added my two cents, as feedback has been requested for TwentySixteen.

**Comment by iamtakashi** [comment]
You have a great point and your feedback is always appreciated. This is a tricky issue and something I'd like to keep thinking the best approach.
