### ISSUE TITLE
Tel Input types are not styled

### ISSUE THREAD

**Issue by mathetos** [WordPress/twentysixteen#323]
The "tel" input type allows mobile users to use their number pad to input fields. See here:
http://www.w3.org/TR/html-markup/input.tel.html

Currently Twenty Sixteen's tel inputs are unstyled. I know it's late in the game, but it would be important  to round out TwentySixteen's mobile experience, and the fix is really easy. See example here:

![tel-fields-unstyled](https://cloud.githubusercontent.com/assets/930724/10236404/f5cc0396-6859-11e5-8586-e4684015982d.png)

**Comment by iamtakashi** [comment]
Are you talking about `tel` or `number`? Isn't the field in the screenshot for `number` type?

**Comment by iamtakashi** [comment]
Maybe not. The number type should have arrows shouldn't it.

But I'm still not sure what the screenshot really means.

**Comment by mathetos** [comment]
I'm referring to "tel". You can see the reference in the link I provided above. It allows mobile phones to use the number pad to enter the numbers in the field (like the Credit Card field which you see in the screenshot as NOT styled) instead of the keyboard.

**Comment by mathetos** [comment]
Sorry, to be a little more explicit: the "Credit Card" field in the screenshot is
`<input type="tel">`

**Comment by iamtakashi** [comment]
Ah, OK. The Credit Number field above uses actually `tel` type. It wasn't very obvious because of the mismatch between the label and the type.

Hmm... The mismatch feels weird and I'm not sure if we should support this kind of case. Is it something a lot of forms do in this mobile era?

**Comment by mathetos** [comment]
It's not unique to this case, the input[type="tel"] is not styled at all like all the other input types. It only requires adding that input type to the same rule as the others, no additional styling. It just needs to be included in the list of input types. 

Regardless of whether it's applied to a telephone number field or credit card field it should also be styled, right?

**Comment by iamtakashi** [comment]
Right. I see your point but If we're going to add style for `tel` type, it opens up a question "Should we style all input type?"

**Comment by iamtakashi** [comment]
In other words, what other types should be added in the CSS?

**Comment by fsylum** [comment]
IMO, following what Bootstrap does, should be fine. Ref: https://github.com/twbs/bootstrap/blob/master/less%2Fforms.less#L97-L112

**Comment by mathetos** [comment]
Well, probably the inputs which are basically a variation of the basic text field should be styled similarly. I mean, styling the "date" input type is ridiculous considering how browsers and OS's handle it. 

I'll try to put together a more comprehensive suggestion a little later tonight, but I think it would still basically be very minimal changes with an overall effect of having a more consistent form experience out of the box regardless of how the inputs are added to a site.

**Comment by mathetos** [comment]
OK, here's all the major input fields according to the current stylesheet:

![form-elements-current](https://cloud.githubusercontent.com/assets/930724/10238810/8cddc8a4-6879-11e5-9224-411ede605f75.jpg)

If we take these lines in style.css:
https://github.com/WordPress/twentysixteen/blob/master/style.css#L615-L627

and change it to this:
`input, textarea {. . .}`
and update this:
https://github.com/WordPress/twentysixteen/blob/master/style.css#L568-L570

to this:

```
input {
    line-height: 1.5;
    margin-bottom: 15px;
}
```

We end up with this:

![form-elements-minor-change](https://cloud.githubusercontent.com/assets/930724/10238836/d32187f6-6879-11e5-924a-042735143504.jpg)

Personally, I would also get rid of the `width: 100%` on the input styles since it's a bit easier to float them when they just inheirt their inline style rather than are forced to a new line because of the width.

Happy to do a PR if this is the direction you want to go (including updating the RTL.css if applicable)

**Comment by mathetos** [comment]
Looks like we're missing a colon and line break here anyway. After background: #f7f7f7

https://github.com/WordPress/twentysixteen/blob/master/style.css#L615-L627

**Comment by iamtakashi** [comment]
I'd say the proposed change is too radical and I can see a number of issues that will need to be adjusted different cases.
- Having line height on input will cause a issue in IEs — text inside will be cut off.
- Having bottom margin will cause double margin when each field is wrapped with `<p>` for example in the comment form.

> Looks like we're missing a colon and line break here anyway. After background: #f7f7f7

? I'm not following. Can you clarify why we need a colon there?

**Comment by iamtakashi** [comment]
I'd say it's safer to add selectors for popular types so that we're not causing new issues with this idea.

**Comment by mathetos** [comment]
I kinda agree, just wanted to put everything on the table. But let's break it up into parts

## Missing Colon
- The background color is not being applied to browsers besides Chrome. Line 622 should be this instead:

```
background: #f7f7f7;
-webkit-linear-gradient(rgba(255, 255, 255, 0), rgba(255, 255, 255, 0));
```

## Line Height/Margin
- Not a problem. Though I did test in IE10 and it was perfectly consistent with the screenshot
- Let's ditch this

## INPUT STYLING
- Originally, this was only about the "tel" input since it is basically a number field. If we paired it down to just fields that were variations of the text field we could do this instead:

```
input[type="text"],
input[type="email"],
input[type="url"],
input[type="password"],
input[type="search"],
input[type="tel"],
input[type="number"],
textarea {
    background: #f7f7f7;
        -webkit-linear-gradient(rgba(255, 255, 255, 0), rgba(255, 255, 255, 0));
    border: 1px solid #d1d1d1;
    border-radius: 2px;
    color: #686868;
    padding: 0.625em 0.4375em;
    width: 100%;
}
```
- Just saw your most recent comment, looks like we're agreed on that.

## Width: 100%
- I'm not sure what the logic is with applying 100% width to the inputs. They are inline elements. Is there a purpose for it?

**Comment by iamtakashi** [comment]
> The background color is not being applied to browsers besides Chrome

Oh, that's a good catch. But then the gradient rule wouldn't have a property :) The purpose for the gradient is to remove the horrible inner shadow and rounded corners from iOS input. We need to add a property `background-image` for that then. I thought the shorthand works but it only worked with webkit.

I'm ok with adding `tel` and `number`.

The reason for the 100% width is mostly visual. I don't like inline labels that cause misalignment of input fields. I also like everything being left align.

**Comment by iamtakashi** [comment]
so, this should work as intended with other browsers.

```
background-color: #f7f7f7;
background-image: -webkit-linear-gradient(rgba(255, 255, 255, 0), rgba(255, 255, 255, 0));
```

**Comment by mathetos** [comment]
OK, I disagree on the width: 100%, but it really doesn't matter so much.

Sending over the PR for the background color issue, and the tel and number fields.
