### ISSUE TITLE
Ping

### ISSUE THREAD

**Issue by psychomuell** [WordPress/twentysixteen#331]
Hi :-)

I'm not a coder, but I think I've found a _ping_ error.
I sent a ping from my subdomain to my blog for testing, My blog shows this errrors:

Fatal error: Call to undefined function the_comments_navigation() in /home/psychomuell/psychomuell.de/wp-content/themes/twentysixteen/comments.php on line 49
03980740dfec8fe1d186f306?s=42&d=blank&r=g, https://secure.gravatar.com/avatar

Maybe this helps? Here you can see: https://psychomuell.de/liebe-webseiten-blogs-verlinkt-euch-wieder-mehr/

I have taken an new account here, because I really like the theme!

**Comment by robertdevore** [comment]
I just tested a ping and see the same error. It doesn't show when I have actual comments on a post.

Someone can correct me if I'm wrong, but `the_comments_navigation()` is a function for with WordPress 4.4, correct? So it'd be an issue with that, and not this theme?

**Comment by robertdevore** [comment]
Found [this changeset](https://core.trac.wordpress.org/changeset/34367) which explains more about the function. Doesn't look like a twentysixteen issue, but again, correct me if I'm wrong.

**Comment by robertdevore** [comment]
FYI, I just tested it with [WordPress 4.4](https://github.com/wordpress/wordpress) and it's working just fine.

I'm not sure if a check to ensure the function exists should be put in place before firing it, but that seems like something that should be explored to ensure backwards compatibility with older versions of WordPress.

**Comment by iamtakashi** [comment]
As it's stated in [readme.text](https://github.com/WordPress/twentysixteen/blob/master/readme.txt) and [here](https://make.wordpress.org/core/2015/10/02/update-on-twenty-sixteen/), Twenty Sixteen _requires_ at least 4.4-alpha now. 

The reason is that a default theme that will be released with a new version of core should not be facilitating older versions of core.
