### ISSUE TITLE
Needs word-wrap for long titles and text

### ISSUE THREAD

**Issue by SeanChDavis** [WordPress/twentysixteen#34]
First noticed this with an actual post title:

![2015-08-29 at 12 12 pm](https://cloud.githubusercontent.com/assets/2359131/9563368/63278a28-4e47-11e5-92d1-871be45ad55b.png)

After looking a little deeper into it and realizing `word-wrap: break-word;` was being used in several places and just happened to miss the title, I took into account where it was being used and made some adjustments.
- It was being applied to `.entry-intro` in two different places, which is always in a post/page article.
- It was being applied to `.entry-content` and `.entry-summary`, which are always in a post/page article.
- It was being applied to `.type-attachment .entry-title` which I'm not even sure is part of the theme (that's a separate issue) but if it was, it would only be in _image.php_, which is always in the aforementioned article element. 
- It was being applied to `.entry-caption`, which is also only part of _image.php_.
- It was being applied to `.textwidget`, which is always going to be nested in `.widget` where it's already applied.

So in all things listed above, it was either 1) unnecessary to have or 2) always in a post/page/attachment article element, which all share the `article[class^="post-"]` selector already in the stylesheet. So I put the word-wrap there.

All other places it's being used in a legit manner, I left it alone.

**Comment by mor10** [comment]
In the current iteration, word-wrap is not applied to `entry-footer` resulting in categories and tags with atypically long single-word names spilling into the main content.

**Comment by SeanChDavis** [comment]
Just noticed that also in the comments area, word-wrap was applied to the comment content but not the entire comment area, leaving the post title hanging as it introduces the comments section:

![2015-08-29 at 7 39 pm](https://cloud.githubusercontent.com/assets/2359131/9565174/c5fe0486-4e85-11e5-9642-e7f6dfca1ce8.png)

Fixed with my commit above.

@mor10 Can you show me a screenshot of what you're referring to? I tried to replicate but it's breaking just fine for me. Thanks.

**Comment by SeanChDavis** [comment]
Honestly, I'm starting to feel like most of the implementations of word-wrap are too generic and its worthy of being in just one CSS rule. I don't see where it would ever hurt.

Thoughts?

**Comment by SeanChDavis** [comment]
It's universal in my PR now. No reason not to be that I can think of.

**Comment by senlin** [comment]
@SDavisMedia don't bother, Core Dev finds this a _non-issue_ labelled as _wontfix_ already since Twenty Fourteen. See [ticket 25008](https://core.trac.wordpress.org/ticket/25008) on Trac.

**Comment by SeanChDavis** [comment]
@senlin Wow. That is absolutely terrible.

**Comment by ihorvorotnov** [comment]
@SDavisMedia yeah, sometimes that english-only-speaking people just don't care about the rest of the world and call it 'too much of an edge case' :)

**Comment by SeanChDavis** [comment]
I noticed! What an ugly ticket.

**Comment by senlin** [comment]
Yup, and it has been for 2 years now and conveniently nobody seems to care that much about these _edge_ cases like for example the entire Dutch language.  

It's threads like that, that set real bad blood between Core Dev vs "the rest".

**Comment by ihorvorotnov** [comment]
@senlin, Dutch and German, to name a few. I've developed websites for both of these languages for my clients. Before this, I thought Russian language has pretty long words, then I met the Dutch language...

**Comment by senlin** [comment]
> I thought Russian language has pretty long words, then I met the Dutch language

:)

I remember a ticket about the menu sidebar in the Dashboard, comments or something is Russian is super-long. Dutch (and indeed also German) have these really silly long words.

Unfortunately Dutch, German and Russian and probably a few more languages are not on the high priority list of WP Core Dev. As long as "normal" English fits, it's good enough...

**Comment by ihorvorotnov** [comment]
Well, if we talk about russian, we should at least add ukrainian, belorussian and bulgarian right away. All are cyrillic and have a lot of long words. Recently I've [asked Automattic's @kovshenin](https://twitter.com/kovshenin/status/637672023305646080) about the number of WP installs in russian. Here are the numbers: 

> 89k core ru_RU package and 136k ru_RU language packs for 4.3.

It's just one language. Just for 4.3 released recently (and we know how many websites are running older versions).

**Comment by senlin** [comment]
I know Konstantin (@kovshenin) too, pity that not even he can convince core of the importance of word-wrap.

**Comment by ihorvorotnov** [comment]
There's also @SergeyBiryukov and @Rarst

**Comment by ianstewart** [comment]
The spirit of the decision against wrapping titles in the previous ticket seemed to me that it's a not-great solution in a _whole bunch_ of languages. The example of antidisestablishmentarianism seemed like a good example of the cure being worse than the disease. That said, in its current iteration Twenty Fifteen  looks nice on the desktop with some real (but rare) "long" (relative to English, I guess) words.

![](https://cldup.com/uZbzLIcwIv.png)

Interestingly, I learned today that it's possible to construct words of sometimes incredible (maybe infinite) length in some languages. It seems though that these long-words are used most often for seemingly rare or poetic or parodic purposes and are uncommon. I'm just going off wikipedia. I'm not an expert. :) Which might make this even more of an edge-case?

**Comment by ianstewart** [comment]
Here's an example of the above text on a smaller screen.

![](https://cldup.com/6r-hxfkLqI.png)

And here, with word-wrap.

![](https://cldup.com/btZMsrTRxV.png)

I'd argue, similar to Lance in the ticket linked above, that while word-wrap does indeed solve the problem of "letters in a word not appearing on the screen" that it isn't a _good_ solution. Both are broken. The "fix" here just seems to be broken in a new way. I'd argue in a worse way but either way it doesn't really seem _better_. (I wish it was!)

**Comment by ianstewart** [comment]
If anyone else, like me, is now fascinated by this, this chart of word-length distributions across a few different languages is really cool:

http://www.ravi.io/language-word-lengths

**Comment by SeanChDavis** [comment]
Definitely interesting. Thanks for that last link, though. Super useful.

I do agree that neither solution is perfect but I think there's a fundamental difference between the two... one breaks the layout [and possibly even hides content] while the other one does. It seems for the last few years, there hasn't been a stand against leaving it "broken" so I don't see how leaving it better (I do think the wrap is better) is not a step in the right direction.

To be clear, though, I'm all for finding a reliable solution if it exists. Right now, it just kills me that one long title can break in the entry title area, the title to the comments area, and even in a sidebar widget showing recent posts or something similar. That seems negligent.

**Comment by ihorvorotnov** [comment]
@ianstewart I agree with your arguments, and even about being an edge case, for any language. And most of the times these long words can be just replaced. However, I don't agree on solution. Leaving them intact actually breaks the things. Wrapping is not a perfect solution, but it prevents things from breaking.

**Comment by SergeyBiryukov** [comment]
> Unfortunately Dutch, German and Russian and probably a few more languages are not on the high priority list of WP Core Dev. As long as "normal" English fits, it's good enough...

Actually, we've fixed all known [language-specific issues with longer strings](https://core.trac.wordpress.org/query?resolution=fixed&summary=~longer+strings&summary=~more+space&summary=~count+doesn%27t+fit&summary=~German+translation&summary=~Russian&summary=~ru_RU&col=id&col=summary&col=reporter&col=owner&col=type&col=status&col=priority&col=milestone&order=id) in core over the years, and [quite a few other I18N tickets](https://core.trac.wordpress.org/query?component=I18N&resolution=fixed&desc=1&order=id).

This one, however, does not seem language-specific, and neither of existing solutions is ideal, as demonstrated above.

**Comment by ianstewart** [comment]
Here's an example using the CSS hyphens property supported in Firefox, IE, and Safari.

![](https://cldup.com/PSOi5dm4_K.png)

![](https://cldup.com/Xoa1SEsIva.png)

http://caniuse.com/#feat=css-hyphens

**Comment by SeanChDavis** [comment]
Ugh... that's so ugly. Can of worms we've got here, I see.

**Comment by ihorvorotnov** [comment]
Hm.. I like hyphens. 
_How could I forget about hyphens? Adding to my toolset._

**Comment by senlin** [comment]
@ianstewart you say that it will never work, but the thing is that you cannot read those languages where you make long words of, so to you it seems unreadable and ugly.

The Dutch word _meervoudigepersoonlijkheidsstoornis_ actually is perfectly readable with the hyphens (although I understand that hyphens are not used by Chrome).

**Comment by senlin** [comment]
@SergeyBiryukov 

> Actually, we've fixed all known language-specific issues with longer strings in core over the years, and quite a few other I18N tickets.

Not sure why you would bring up a completely different topic here? Are you now trying to justify to leave something broken, because **you did so much other stuff already**?

You know what, forget that I chimed in, this is so typical behaviour of you Core people. 

Done with this shit!

**Comment by philiparthurmoore** [comment]
Outside of maintaining [_s](https://github.com/Automattic/_s), this is the first time I've ever interacted with so many WordPress people on GitHub. On Trac tickets are harder to find and harder to take part in, and the tone is, at times, somewhat contentious.

One thing I love about GitHub so much is that it feels light, positive, and collaborative, so much more so than Trac. As a contributor, I was hoping that by 2016 being brought to GitHub we would all realize how wonderful the strides that Core is taking to gather input, involve us all, and create a sense of positivity and togetherness around the code and design decisions for the new default theme.

> You know what, forget that I chimed in, this is so typical behaviour of you Core people. Done with this shit!

I can't speak for everyone else, and I'm not on Core, so I'll ask you this (and others) as a fellow contributor to the project hoping to make something great: can we please tone down the aggressive and negative attitude? Some solutions that we deeply want in 2016 will be accepted. Some won't. Those are the breaks. We're all real people with real feelings putting in real time to come up with something amazing, and it's hurtful for something so collaborative to feel so combative. If I were a new contributor to the WordPress project and stumbled on this entire exchange I would have very little feeling to want to help. Let us be advocates for professionalism.

A lot can change in two years. For history it's interesting to link to an old Trac ticket but maybe things have changed since then. Maybe the developers who once said No feel like Yes this time (or not). I change my mind every week about something. I'm still not sure how I feel about the word wrapping issue. It can get very ugly very quickly with English words and Vietnamese doesn't even really use the hyphen 99.9999999% of the time ([unscientific](https://en.wikipedia.org/wiki/Vietnamese_morphology)). But reading @SDavisMedia's comments, I can't help but agree with his sentiment of design negligence:

> Right now, it just kills me that one long title can break in the entry title area, the title to the comments area, and even in a sidebar widget showing recent posts or something similar. That seems negligent.

There are several choices here: 1) fix the word wrapping; 2) don't fix the word wrapping; 3) make the text much smaller on mobile screens so that if word wrapping is or isn't fixed hyphens don't completely destroy the design; 4) introduce word wrapping only for languages that have demonstrated a great need for it; 5) put an overflow hidden on layout blocks that long strings might break and make users sad when their titles go bye-bye.

For advocates of word wrapping, it would probably be very helpful to add real world examples (screenshots!) of where the current solution breaks down. Not fictitious words or strings but real words and real content where this breaks. I think that would help personalize this bug and move it away from "edge case" territory, which can be just another way for a developer unwilling to dig further into this of saying not my problem.

**Comment by ianstewart** [comment]
> you say that it will never work

I probably should have noted that I like the hyphens. Like @ihorvorotnov I also forgot about them.

**Comment by ianstewart** [comment]
This was discussed a bit in core-themes in Slack.

https://wordpress.slack.com/archives/core-themes/p1441642643000076

**Suggestion:** Add hyphenation for browsers that support it in titles and titles-only. Fallback to current status.

**Comment by SeanChDavis** [comment]
Alright I started fresh and added `hyphens: auto;` (with vendor prefixes) to just the necessary elements: entry-title, comments-title, and post navigation post-title... that's it. I also added the recommended `word-break: break-all;` fallback for hyphens. Again, though, this only applies to those three title elements. 

![screen shot 2015-09-07 at 3 33 27 pm](https://cloud.githubusercontent.com/assets/2359131/9722608/d680241e-5575-11e5-8782-fac95de6b174.png)

![screen shot 2015-09-07 at 3 34 06 pm](https://cloud.githubusercontent.com/assets/2359131/9722613/e7ff492c-5575-11e5-8057-3e184c8fdf0e.png)

Let me know what you all think.

**Comment by SeanChDavis** [comment]
Sorry, those are Chrome which use the fallback. Here's what it looks like in browsers that have hyphen support:

![screen shot 2015-09-07 at 3 36 24 pm](https://cloud.githubusercontent.com/assets/2359131/9722638/38679d24-5576-11e5-8cb7-84df2b6dd34c.png)

---

Bottom line, it works in all browsers, though the appearance is not consistent. No broken layouts, though.

**Comment by karmatosed** [comment]
This current PR seems to do more than just titles, unless I'm wrong.

**Comment by SeanChDavis** [comment]
@karmatosed The decision made in the Slack conversation was to add it to titles but not the body. I added it to post titles, the same title that displays above the comments: "One thought on {post_title}, and the post navigation titles... all legit titles. http://glui.me/?i=8lqvgh0p3lu0fkl/2015-09-07_at_6.31_PM_(1).png/

Why would we fix the title in one location and not the other locations?

**Comment by karmatosed** [comment]
@SDavisMedia, right I was in meeting also. Your patch seems to go a bit further.

**Comment by SeanChDavis** [comment]
@karmatosed It would help if you'd be more specific. This is the feedback I'm getting from @iamtakashi: https://github.com/WordPress/twentysixteen/pull/131#commitcomment-13108197

**Comment by karmatosed** [comment]
Sure. My point was you highlight comment and also post navigation titles. In our chat we talked about titles. Your patch brings in comment titles and navigation.

**Comment by karmatosed** [comment]
After having a chat with @iamtakashi, it's a design decision to do all titles and I'm absolutely fine with that.

**Comment by SeanChDavis** [comment]
@karmatosed Oh okay. Correct, because this makes no sense: http://glui.me/?i=gdw0bodg48j6ni1/2015-09-08_at_8.11_AM.png/ I'm willing to remove it if a discussion says I should do so. But I'm pretty sure when he said [this](https://wordpress.slack.com/archives/core-themes/p1441642862000087), he was using "titles" as a distinction between title text and body text... not specifically saying on entry titles only.

**Comment by SeanChDavis** [comment]
Sorry... just saw your last message, @karmatosed. :+1:

**Comment by iamtakashi** [comment]
Yes, I meant all titles including ones in the post navigation and the comment title. I should've made it clear in the chat.

Now I wonder if we should apply the word wrap rule to more broadly, and add hyphens to only the aforementioned titles. So we can remove the word wrap rule from the current stylesheet. But I'm hesitant to apply it with the universal selector. I don't have any backup test case or anything but I don't want to cause unexpected broken look.

Any opinion?

**Comment by SeanChDavis** [comment]
That's the original conclusion I came to (minus the hyphens) because as I added adjustments to multiple elements, I noticed that I was needing to go more and more broad. That's why I ended up just going universal. Can't say I'm a huge fan of repeating the same CSS multiple times throughout the stylesheet if we don't have to.

I have about a dozen or so themes released (including two on .org) and I have never ran into any universal word-wrap issues. That's the only test case I have, though. The thing is, if you look at everywhere word-wrap was/is already being applied in Twenty Sixteen, we're applying it to multiple individual elements that are all within one element. This is happening in both the `#primary` column and the `#secondary` column. At that point, it only makes sense to hit them both once... or even better, hit the entire site structure once considering there isn't much left after those two columns.

That alone will handle the titles. But even if we make a few more adjustments to target the titles specifically (perhaps with hyphens and changing the word-wrap values), what I mentioned above still applies to the rest of the site HTML content and the way word-wrap is currently being applied to it.

**Comment by karmatosed** [comment]
Noting this is flagged for discussion in the next meeting: Friday 16:00 UTC in #core-themes.

**Comment by SeanChDavis** [comment]
Sweet.

**Comment by karmatosed** [comment]
We discussed this today in the weekly meeting @SDavisMedia, we need a refresh PR. It would be great to investigate rounding up the slectors into one statement. Or at least to explore that.

**Comment by SeanChDavis** [comment]
This gets messier every time more changes have to be made while others are getting merged. So I scrapped my fork and started over again.

The most recent PR consolidates the `hyphen` CSS in what I felt was the most logical position in the stylesheet. Word-wraps were left as they were. 

@karmatosed, let me know if this is not what you meant in your last comment please. And if it's not, please explain in detail exactly what you all want and I'll make it happen.

**Comment by ihorvorotnov** [comment]
For me #161 looks fine.

**Comment by iamtakashi** [comment]
Fixed in #161
