### ISSUE TITLE
Enable Support for Responsive Images

### ISSUE THREAD

**Issue by tevko** [WordPress/twentysixteen#344]
[In light of the recent merge of the RICG-responsive-images plugin into WP core](https://github.com/aaronjorbin/develop.wordpress/commit/fabd554bb2588f0ca52383128186adf9ba469329), it would be great to see full responsive image support (using `srcset` and `sizes` attributes on the image tag) find its way into the Twenty Sixteen  theme. 

While the recently merged patch ensures that valid `srcset` attributes will be added to featured and content images, intermediate image sizes (outside of the default sizes created by WordPress) and the `sizes` attribute on the image tag, are open to customization by theme developers so that their themes can take full advantage of the new feature.

If Twenty Sixteen were to add these customizations, it would serve as a blueprint for theme developers looking to understand and make best use of the new responsive image feature, while also serving as a front end performance improvement.

[More on the feature and plugin can be found here](https://github.com/ResponsiveImagesCG/wp-tevko-responsive-images)

**Comment by karmatosed** [comment]
Hey @tevko, would it be possible to have a PR for this?

**Comment by tevko** [comment]
@karmatosed Will have one shortly!

**Comment by karmatosed** [comment]
Awesome! Look forward to it.

Note: eep sorry closed by accident.. reopened.

**Comment by tevko** [comment]
PR #347

**Comment by ghost** [comment]
Nice!

**Comment by tevko** [comment]
PR updated - #348
