### ISSUE TITLE
Meta Navigation in Footer for Links like Impressum, Contact, About

### ISSUE THREAD

**Issue by ghost** [WordPress/twentysixteen#351]
The new theme 'twenty sixteen' is specially nice.

It would be desirable to have an optional meta navigation in the footer. The navigation should placed on every site, post and overview – including homepage. It could be for pages like impressum, contact or about.

Thank you all for your work.

Your sincerely
Dominik

**Comment by robertdevore** [comment]
Do you mean having this automatically added in, or as an option for the user to add a custom menu to the section in the footer?

**Comment by ghost** [comment]
I think it should be an optional menu as well as the footer menu for social links.

I would prefer an menu optionally. As well as the footer menu for social links.

For example: "Home | About | Impressum" or "Home · About · Impressum"

**Comment by robertdevore** [comment]
Where would you place them? Under the copyright? Inline with the copyright?

**Comment by ghost** [comment]
Inline with the copyright or above the copyright? Otherwise it could be as an footer widget on every page (inkl. homepage). But i'm not an designer.

**Comment by robertdevore** [comment]
It looks like the theme already has a footer menu option built in that shows the primary navigation menu.

**Comment by ghost** [comment]
Yes a footer widget is there, but not on every site (eg. blog main site is without)

**Comment by karmatosed** [comment]
I think we have enough options for now. At this late stage adding something is also not desirable. There is also the option of a child theme if you want to add more things.
