### ISSUE TITLE
User Documentation

### ISSUE THREAD

**Issue by brentlogan** [WordPress/twentysixteen#352]
I'd like to see Twenty Sixteen distributed with documentation aimed at users, not just developers. This could include theme-specific items, such as:
1. How the theme uses excerpts.
2. How to use the theme with and without a sidebar.
3. Which image sizes should be used, such as how to duplicate the large image in the theme screenshot (I have been unable to get an image to exceed the text margins other than for featured images).
4. How to use the social media menu.

I'm sure there could be other items as well.

**Comment by karmatosed** [comment]
I'm keen we don't have more files to add documentation. If this can be added to the readme in some form, that's the best route. How about you try and work on a pull request?

**Comment by brentlogan** [comment]
@karmatosed I'm fine with not adding more documentation. In reviewing the readme, I see there's already a link to the codex page for use and customization (although it's a placeholder for now).

I wonder how the typical WordPress user ever finds readme.txt.  I wouldn't expect the typical user to download any theme or browse the code. It's just so much easier to install themes from the WordPress backend.

It looks like WordPress.org themes directory and the WordPress backend (appearance > themes > Theme Details) are now displaying only the Description portion of readme.txt. Should the link to the codex be moved to that portion?

**Comment by karmatosed** [comment]
I personally think it's fine, but lets see what @iamtakashi thinks.

**Comment by iamtakashi** [comment]
Theme description on `/themes.php` isn't from readme.txt, but the one in `style.css`.

@karmatosed, Does TRT have any policy about having a link in the theme description in `style.css`?

**Comment by karmatosed** [comment]
I'm not keen we add a link, no. That's why I think things are ok. It wouldn't actually show as a proper link. It would be www.something.com rather than a href.

**Comment by iamtakashi** [comment]
> It wouldn't actually show as a proper link. It would be www.something.com rather than a href.

A link properly displayed on `/themes.php` but I can see why TRT doesn't like to have a link in description  (abusing it to spam etc.)

So the only option if we want to add extra documentation is readme.txt.

**Comment by brentlogan** [comment]
Both WordPress Themes and the Twenty Sixteen back end display:

> Twenty Sixteen is a modernized take on an ever-popular WordPress layout — the horizontal masthead with an optional right sidebar that works perfectly for blogs and websites. It has custom color options with beautiful default color schemes, a harmonious fluid grid using a mobile-first approach, and impeccable polish in every detail. Twenty Sixteen will make your WordPress look beautiful everywhere.

The style.css headed doesn't include this text, but:

```
/*
Theme Name: Twenty Sixteen
Theme URI: https://wordpress.org/themes/twentysixteen/
Author: the WordPress team
Author URI: https://wordpress.org/
Description: Twenty Sixteen is a modernized take on an ever-popular WordPress layout — the horizontal masthead with an optional right sidebar that works perfectly for blogs and websites. It has custom color options with beautiful default color schemes, a harmonious fluid grid using a mobile-first approach, and impeccable polish in every detail. Twenty Sixteen will make your WordPress look beautiful everywhere.
Version: 0.1.20150828
License: GNU General Public License v2 or later
License URI: http://www.gnu.org/licenses/gpl-2.0.html
Tags: black, blue, gray, green, white, yellow, dark, light, one-column, two-columns, right-sidebar, fixed-layout, responsive-layout, accessibility-ready, custom-background, custom-colors, custom-header, custom-menu, editor-style, featured-images, flexible-header, microformats, post-formats, rtl-language-support, sticky-post, threaded-comments, translation-ready
Text Domain: twentysixteen
This theme, like WordPress, is licensed under the GPL.
Use it to make something cool, have fun, and share what you've learned with others.
*/
```

I browsed the popular themes on WordPress, hoping to find one with a real link in the description. The only one I found with any links was [Accesspress Lite](https://wordpress.org/themes/accesspress-lite/), but they're just bare un-anchored links like @iamtakashi described above.

I'd love to have the theme documentation linked on Twenty Sixteen's back end, but it doesn't seem possible to do easily and elegantly. 

Probably the nicest solution would be a "Help" section in Customizer that displays links to the documentation and the WordPress support forums, but that's a big ask this late in Twenty Sixteen's development.

**Comment by iamtakashi** [comment]
> The style.css headed doesn't include this text

? Just to be clear, as I mentioned before, the text is from `Description`  after `Author URI` in the header in style.css.

Anyway, the .org theme directory doesn't show a link so that's out of option.

**Comment by karmatosed** [comment]
Tentatively closing this now. We can revisit in meeting if I'm doing this prematurely.
