### ISSUE TITLE
entry-footer line artifact in long names

### ISSUE THREAD

**Issue by mor10** [WordPress/twentysixteen#37]
When a long name is displayed, the hidden "/" separator drops down to the next line creating an empty line artifact in the `entry-footer` area. Patch to follow.

![line-artifact](https://cloud.githubusercontent.com/assets/1132200/9563630/596524a4-4e3e-11e5-8337-77d7c0d14318.PNG)

**Comment by SeanChDavis** [comment]
Just to make sure you noticed, it happens for _all_ the elements in the byline. I just noticed the same thing at the end of a categories listing. :+1: 

![2015-08-29 at 1 17 pm](https://cloud.githubusercontent.com/assets/2359131/9563654/8708a3c4-4e50-11e5-8d2f-fcbbe2097d39.png)

**Comment by mor10** [comment]
My patch addresses the underlying problem which is the method of hiding the separator artifacts added for smaller screens.
