### ISSUE TITLE
all image sizes at content, the theme or core I don't know

### ISSUE THREAD

**Issue by MonikaTS** [WordPress/twentysixteen#372]
this morning I did a responsive image test.
only developer plugins are active, WP nightly build and twenty sixteen from "last night". 
I upload a new image, insert this image with 300px width
after this I have all larger image sizes at source and this doesn't make sense too me.

`<img src="xx/media/2015/11/IMGP9685-300x199.jpg" alt="IMGP9685" 
    width="300" height="199" class="aligncenter size-medium wp-image-750"`

```
`srcset="xx/media/2015/11/IMGP9685-250x166.jpg 250w, 
xx/media/2015/11/IMGP9685-300x199.jpg 300w, 

xx/media/2015/11/IMGP9685-768x511.jpg 768w, 
xx/media/2015/11/IMGP9685-1024x681.jpg 1024w, 
xx/media/2015/11/IMGP9685.jpg 1029w" sizes="(max-width: 300px) 85vw, 300px" `
```

**Comment by iamtakashi** [comment]
Some details might have been changed but maybe you'll find this article from @tevko helpful.

http://www.smashingmagazine.com/2015/02/ricg-responsive-images-for-wordpress/
