### ISSUE TITLE
select not being styled

### ISSUE THREAD

**Issue by brentlogan** [WordPress/twentysixteen#378]
It looks like the select element should be added to the selector around line 628 of style.css. This would style it consistently with the other form input fields.

```
input[type="text"],
input[type="email"],
input[type="url"],
input[type="password"],
input[type="search"],
input[type="tel"],
input[type="number"],
textarea,
select {
    background: #f7f7f7;
    background-image: -webkit-linear-gradient(rgba(255, 255, 255, 0), rgba(255, 255, 255, 0));
    border: 1px solid #d1d1d1;
    border-radius: 2px;
    color: #686868;
    padding: 0.625em 0.4375em;
    width: 100%;
}
```

Without suggested change:

![without](https://cloud.githubusercontent.com/assets/14060692/11162382/1064852c-8a54-11e5-8288-e72c1e6d263b.jpg)

With suggested change:

![with](https://cloud.githubusercontent.com/assets/14060692/11162383/1ad785cc-8a54-11e5-9a4f-3f155c6b9e74.jpg)

**Comment by iamtakashi** [comment]
I'm not crazy about this idea. In my experience, select element is better to leave it with default browser style. 

Have you checked different browsers in each OS and mobile? Chrome, Safari, Firefox, Opera, Versions of IE, Windows, Mac, iOS, and Android?

Related: https://github.com/WordPress/twentysixteen/issues/373

**Comment by brentlogan** [comment]
I have tried it with Chrome, Edge, and Firefox on desktop and Chrome, Firefox, and AdBlock Browser on Android. It effects only the initial display of the dropbox, not what appears when the box is active.

I much prefer it.

In a somewhat related matter, on narrow screen widths, text breaks in mid-word. I added `word-wrap: normal;` in an attempt to fix this, but now too long text displays in a single line with overflow hidden.

You can see my proposed change on my blog here:

[http://brentlogan.com/2015/11/peace-for-paris/](http://brentlogan.com/2015/11/peace-for-paris/)

Maybe those with access to other OSes and browsers could look and comment.

**Comment by karmatosed** [comment]
I agree with @iamtakashi on this. We shouldn't start fiddling with the default browser style for select elements.

**Comment by iamtakashi** [comment]
Just to add my additional note: regardless we like it or not, the browser default style for select element is the most recognisable, and users are familiar with it the most. Keeping the default style will deliver the best experience to users.

**Comment by brentlogan** [comment]
I fail to see how a select dropdown box that is styled similarly to the rest of the form fields, but retains the drop down indicator on the right is confusing. My proposal only changes the initial styling of the element, not the drop down options that appear when clicking on the select field.

Regardless, whatever you guys prefer goes. It's not hard for the rest of us to modify the default behavior.

Thanks!
