### ISSUE TITLE
Title without Markup

### ISSUE THREAD

**Issue by schoenwaldnils** [WordPress/twentysixteen#379]
The post title doesn't render italic bold styles.

> Verify that:
> The post title renders the word “with” in italics and the word “markup” in bold.
> The post title markup should be removed from the browser window / tab.

**Comment by iamtakashi** [comment]
1. Make sure you have actually `<em>` around "with" in the title.
   ![screen shot 2015-11-15 at 15 57 43](https://cloud.githubusercontent.com/assets/908665/11169493/98cce2b6-8bb1-11e5-92f7-39bfa39fd7c0.png)
2. Unfortunately <a href="https://www.google.com/fonts/specimen/Montserrat">Montserrat</a>, does not have italic so it will be a fake italic but I don't think it's a big deal as I see it as an edge case.

**Comment by karmatosed** [comment]
Closing as discussed in this week's meeting. This behaves as we expect.
