### ISSUE TITLE
Updating theme to 0.1.20151117 breaks site

### ISSUE THREAD

**Issue by slash1andy** [WordPress/twentysixteen#380]
You get this error: Twenty Sixteen requires at least WordPress version 4.4. You are running version 4.3.1. Please upgrade and try again.

It then reverts back to the last default theme (2015). WordPress is only on 4.3.1, so it's kind of impossible to be on 4.4

![](http://cld.wthms.co/bRe3/2caqqL8R+)

**Comment by iamtakashi** [comment]
Twenty Sixteen now requires at least 4.4-alpha: https://make.wordpress.org/core/2015/10/02/update-on-twenty-sixteen/ It is also mentioned in <a href="https://github.com/WordPress/twentysixteen/blob/master/readme.txt">readme.txt</a>

You can install <a href="https://wordpress.org/plugins/wordpress-beta-tester/">WordPress Beta Tester Plugin</a> or <a href="https://codex.wordpress.org/Installing/Updating_WordPress_with_Subversion">install trunk with Subversion</a>. 

In hindsight, we should've made it require the trunk from the beginning but then the contributions wouldn't have been the same.
