### ISSUE TITLE
Sync latest wordpress.org version number

### ISSUE THREAD

**Issue by r-a-y** [WordPress/twentysixteen#381]
It only appears that the theme version number is behind.

That, and the related enqueued CSS/JS version numbers.  You guys might be using some type of build process, but thought I'd mention this.

**Comment by iamtakashi** [comment]
@r-a-y, version number for CSS and JS is basically the last date when each file has been edited but it might not be accurate precisely.

@karmatosed, we've discussed the theme version number before and that time we said to see if we can increment automatically when we sync it with the .org theme repo.

**Comment by karmatosed** [comment]
@dd32 we discussed this before, is this possible to increment numbers?

**Comment by dd32** [comment]
@karmatosed Sorry, I guess it slipped through the cracks.

No. I'm not going to setup automated updates of the version number in Github though now. The days of syncing the dev release are extremely numbered (Once 1.0 is released with 4.4, syncing will have to be disabled permanently) and it offers no significant benefit IMHO if it hasn't been an issue during development.

**Comment by r-a-y** [comment]
Thanks for responding everyone.

I'm going to close this based on dd32's feedback, but feel free to reopen if necessary.
