### ISSUE TITLE
Add singular.php

### ISSUE THREAD

**Issue by mathetos** [WordPress/twentysixteen#39]
Since TwentySixteen is a showcase of what WordPress can do, should the new singular.php file be provided in the theme despite the fact that single.php and page.php are already provided?

**Comment by mathetos** [comment]
On closer look, it might be fairly elegant to do some conditional logic to check whether it's a post or a page and output the content-page or the content-single. Could do the same for post navigation then it's all handled fairly DRY and only one file instead of two.

**Comment by SeanChDavis** [comment]
In addition to @grappler's comment on the PR, I think some of this needs to be rewritten anyway. 

The switch statement is a bit much. 3 of the 4 cases use the same template file. Much simpler conditional logic could be used as there aren't many different possible cases.

Also, why is `$posttype` an empty string? It's empty throughout the entire switch statement. All post types are using the `default` case. `$posttype` should get its value from `get_post_type()` for that switch statement to work properly (the conditional logic should still be rewritten, though).

**Comment by mathetos** [comment]
Good comments. I'll re-submit with it a bit cleaner.

**Comment by mathetos** [comment]
I'll clarify that I've read that switch statements perform much better than if statements. But at this level I think the difference is totally inconsequential and you're right that it would really just be one if and an else.

**Comment by SeanChDavis** [comment]
@mathetos Oh definitely I didn't mean that switch statements are bad. Sorry if it came off that way. 

It's just that in this particular case, given that `get_template_part()` even has a built-in fallback system of its own, only one of two files are being called in all cases. So it was just overkill here.

**Comment by ianstewart** [comment]
@mathetos Can you provide a refreshed PR here?

**Comment by mathetos** [comment]
I will absolutely.

**Comment by mathetos** [comment]
Cleaning it up now for the new PR. Sorry for the delay.

**Comment by mathetos** [comment]
Refreshed PR added here: https://github.com/WordPress/twentysixteen/pull/144

**Comment by mathetos** [comment]
Lastest PR passes all Travis tests: https://github.com/WordPress/twentysixteen/pull/199

**Comment by karmatosed** [comment]
Updated all labels to reflect the fact we're going to have this in. We now need a confirmation test before merge.
