### ISSUE TITLE
Sanitize/Escape localized strings?

### ISSUE THREAD

**Issue by wpexplorer** [WordPress/twentysixteen#391]
I see some `__()` and `_e()` usage in the theme as opposed to their escaped counter parts: `esc_attr__ , esc_attr_e, esc_html__ , esc_html_e`

https://vip.wordpress.com/2014/06/20/the-importance-of-escaping-all-the-things/

**Comment by iamtakashi** [comment]
See #300

**Comment by wpexplorer** [comment]
@iamtakashi Thanks for the link! So is escaping localized strings not a requirement for WordPress.org themes? In the thread you posted @karmatosed mentions "we are simply doing it before" but with the localized strings this isn't the case since `__()` nor `_e()` are escaped in any way prior to output - https://core.trac.wordpress.org/browser/tags/4.3.1/src/wp-includes/l10n.php#L0

Just trying to figure out how important it is for these strings to be escaped since it seems WordPress.com requires it (maybe I am wrong about that though) as well as marketplaces like ThemeForest.

Thank you for clarifying!

**Comment by iamtakashi** [comment]
> So is escaping localized strings not a requirement for WordPress.org themes?

I can't really speak for Theme Review Team. @karmatosed?

**Comment by iamtakashi** [comment]
@wpexplorer, Worth noting this thread: https://core.trac.wordpress.org/ticket/30724

**Comment by wpexplorer** [comment]
Thanks!
