### ISSUE TITLE
Social links placement for excerpts below the entry title

### ISSUE THREAD

**Issue by mtomas7** [WordPress/twentysixteen#397]
Hello,

I noticed that plugins like Floating Social Bar places its icons also for top excerpt, please see image. This capture is of a single post.

![clipboard01](https://cloud.githubusercontent.com/assets/2348962/11886712/cf643dec-a4f2-11e5-84d2-53a83bb7a275.jpg)

Should the theme be changed to avoid this behavior or it is a plugin's fault?

Thank you!

**Comment by iamtakashi** [comment]
A default theme won't change because of a particular plugin :)

Jetpack sharing button has been adjusted to not show up there. I'm not saying the plugin should do the same but just FYI.

**Comment by brentlogan** [comment]
I think this could have been an easy fix. In the function `twentysixteen_excerpt`, replace `<?php the_excerpt(); ?>` with 

```
     <?php
        $my_excerpt = get_the_excerpt();
        echo $my_excerpt;
     ?>
```

Twenty Sixteen is admittedly using the excerpt in a ground-breaking fashion. A little backward compatibility is a good thing, IMHO.

**Comment by mtomas7** [comment]
Thank you for this fix, now I can use this approach in my theme! :)

P.S. and nobody got hurt by implementing this.

P.P.S. Default WP themes should show good example for other developers.

**Comment by brentlogan** [comment]
Even if Twenty Sixteen is not modified, all is not lost: `twentysixteen_excerpt` has been written to be able to be overridden in a simple plugin. No editing of the theme files is necessary.
