### ISSUE TITLE
Suggestion for no-js detection script

### ISSUE THREAD

**Issue by bryanwillis** [WordPress/twentysixteen#408]
In [functions.php](https://github.com/WordPress/twentysixteen/blob/65b8e3dee4a318e80c102da6d8a853b53ee8f44f/functions.php#L224) the javascript detection script is implemented by a hook to wp_head. This seems inefficient since  `class="no-js` is [hardcoded into the head](https://github.com/WordPress/twentysixteen/blob/65b8e3dee4a318e80c102da6d8a853b53ee8f44f/header.php#L13). Why have a callback to add/remove the script to `wp_head` if we can't remove the html class without deleting it from the header. It seems to me like it should work one of two ways.

1) Have **BOTH** the  js detection script and `class="no-js` hardcoded:

``` php
<html <?php language_attributes(); ?> class="no-js">
<head>
    <meta charset="<?php bloginfo( 'charset' ); ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script>(function(html){html.className = html.className.replace(/\bno-js\b/,'js')})(document.documentElement);</script>
...
...
```

2) There are a few ways of doing this, but make both editable through filters/hooks:

``` php
function twentysixteen_javascript_detection_class($output) {
    return $output . ' class="no-js"';
}
add_filter( 'language_attributes', 'twentysixteen_javascript_detection_class' );

function twentysixteen_javascript_detection() {
    if ( has_filter( 'language_attributes', 'bsg_js_detection_lang_atts' ) ) {
        echo "<script>(function(html){html.className = html.className.replace(/\bno-js\b/,'js')})(document.documentElement);</script>\n";
    }
}
add_action( 'wp_head', 'twentysixteen_javascript_detection', 0 );
```

The second option would allow the developer to do something like `remove_filter( 'language_attributes', 'twentysixteen_javascript_detection_class' );` and be done with it instead of having to delete code from header.php if they chose to `remove_action( 'wp_head', 'twentysixteen_javascript_detection' );`. 

Anyway, just a thought. There might be a better way to do this or a reason why you guys haven't included it by default that I'm not realizing!

**Comment by ihorvorotnov** [comment]
The second option (adding `no-js` class via `language_attributes` filter) is a bit hacky. However, I agree that replacing hardcoded class seems logical. Maybe, smth like

```
<html <?php language_attributes(); ?> <?php javascript_support(); ?>>
```

and

```
function javascript_support() {
    $attribute = 'class="no-js"';
    echo apply_filters( 'javascript_support', $attribute );
}
```

**Comment by iamtakashi** [comment]
No.1 is out of option to respect Theme Review Team. (<a href="https://make.wordpress.org/themes/handbook/review/required/#stylesheets-and-scripts">#</a>)

> No hard coding of scripts, styles and Favicons unless a browser workaround script. Everything should be enqueued.

**Comment by emiluzelac** [comment]
@iamtakashi :+1:

**Comment by bryanwillis** [comment]
<blockquote>No hard coding of scripts, styles and Favicons unless a browser workaround script. Everything should be enqueued.</blockquote>


add_action('wp_enqueue_scripts', function() {
        wp_enqueue_script( 'dd_belatedpng',
            get_template_directory_uri() . '/js/dd_belatedpng.js', 
            array(), 
            '1.0.0', 
            false 
        );
        wp_script_add_data('dd_belatedpng', 'conditional', 'lt IE 7');
});

add_action('wp_head', function(){
   if (wp_script_is( 'dd_belatedpng', 'enqueued' )) {
       echo '' . "\n";
   }
});

Thank you for helping me validate my point @iamtakashi :). 


@iamtakashi this is essentially this



This is essentially the reason I posted

Didn't really think no. 1 was an option, but it helps demonstrate the issue here.


window.addEventListener("load", function () {
    document.body.className.replace(/\bno-js\b/,'js');
}, false);


/** 
 * Javascript Detection Filter
 * 
 * remove_filter( 'language_attributes', 'lang_atts_js_detect' ); 
 */ 
add_filter( 'language_attributes', 'lang_atts_js_detect' );
function lang_atts_js_detect($output) {
    return $output . ' class="no-js"';
}
add_action( 'wp_head', function() {
    if ( has_filter( 'language_attributes', 'lang_atts_js_detect' ) ) {
        echo "<script>(function(html){html.className = html.className.replace(/\bno-js\b/,'js')})(document.documentElement);</script>\n";
    }
}, 0);

```php
/** 
 * Javascript Detection Theme Support
 * 
 * add_theme_support( 'js-detect' ); 
 */ 
add_action( 'init', function() {
    if ( current_theme_supports( 'js-detect' ) && !is_admin() )
        add_filter( 'language_attributes', 'lang_atts_js_detect_class' );
        add_action( 'wp_head', 'lang_atts_js_detect_script', 0 );
}
function lang_atts_js_detect_class($output) {
    return $output . ' class="no-js"';
}, );
function lang_atts_js_detect_script() {
    echo "<script>(function(html){html.className = html.className.replace(/\bno-js\b/,'js')})(document.documentElement);</script>\n";
}
```

```php
function lang_atts_js_detect_script() { ?>
<noscript>
<style type="text/css">.no-js .site-header-menu { display: block; } .no-js .main-navigation ul ul { display: block; }</style>
<script type="text/javascript">(function(html){html.className = html.className.replace(/\bno-js\b/,'js')})(document.documentElement);</script>
</noscript>
<?php
}
```



<script>document.body.className = document.body.className.replace(/\bno-js\b/,'js');</script>






class Genesis_Js_No_Js {
	public function run() {
		add_filter( 'body_class', array( $this, 'body_class' ) );
		add_action( 'genesis_before', array( $this, 'script' ), 1 );
	}
	public function body_class( $classes ) {
		$classes[] = 'no-js';
		return $classes;
	}
	public function script() {
                 echo "<script>(function(html){html.className = html.className.replace(/\bno-js\b/,'js')})(document.documentElement);</script>\n";
	}
}
$genesis_js_no_js = new Genesis_Js_No_Js;
$genesis_js_no_js->run();




https://github.com/WordPress/twentysixteen/blob/5f1225063e1823c27a6a805b8f22dfa9ee31dac0/style.css#L819-L826

**Comment by bryanwillis** [comment]
I agree @iamtakashi that the No. 1 is the worst option here. I included it to try and get the point across that it cant go both ways :)

Breaking down the Theme Review Team guidelines:
- No hard coding of scripts styles... unless a browser workaround script
- Everything should be enqueued.
- No minification of scripts or files unless provide original files.

There are several reasons that scripts/styles should be enqueued and not hardcoded as you guys know....

Just to name a couple:
- avoid duplicate scripts since you can't enqueue scripts with the same handle 
- makes it easier for child themes to override without having to edit parent themes directly by dequeuing 

The way we are doing it now we are essentially **hard coding** `no-js` meaning that it can only be removed by deleting. On top of that, if a novice developer thinks they can remove it by unhooking `twentysixteen_javascript_detection`, they will most likely think there is a bug or they broke something since no-js classes are going to be applied. I haven't had a chance to use twenty-sixteen yet, but I'm guessing it would affect the appearance of the menus or other parts of the theme. In the end they would have to edit out no-js out of the `header.php` which is what we're trying to avoid. We're also minifying and not enqueuing the function which goes against that Theme Review section posted.  As for the browser workaround part, what actually qualifies as that? I would assume this was a browser workaround, is it not?

Anyway, I definitely agree 2 or 3 are better options. In terms of option 2 being a hack, it's really not a hack at all if you look at how the `language_attributes` function works. Adding an entirely new function seems like overkill, but if again the idea is to make it easy for new developers to learn and understand wordpress so maybe an extra function makes since if you guys think that people would get confused by the "language_attributes" name.

I usually use genesis for developing and do something like this in a plugin or helper function file:

``` php
add_action('wp_loaded', 'genesis_javascript_detection');
function genesis_javascript_detection() {
    if (current_theme_supports('javascript-detection')) {
        add_action( 'genesis_before', 'genesis_javascript_detection', 0 );
        add_filter('body_class', 'genesis_javascript_detection_body_class');
    }
}
function genesis_javascript_detection_script() {
    echo "<script>document.body.className=document.body.className.replace(/\bno-js\b/,"js");</script>\n";
}
function genesis_javascript_detection_body_class($classes) {
    $classes[] = 'no-js';
    return $classes;
}
```

This seems the cleanest and makes the most sense to me, but I don't think it's possible to do without adding some sort of event listener for when the body tag is loaded in the DOM since the script would be output in the head in twenty sixteen...

I'm sure someone has a better solution out there than all of these so please chime in if you do !!

**Comment by karmatosed** [comment]
I'm not seeing a solution here that would work for the theme review. As such, lets close this up for now. If we can show this is required and works within guidelines for theme review and core; we can reopen with a patch.
