### ISSUE TITLE
In mobile view, search box is not in obvious location

### ISSUE THREAD

**Issue by srikanta00** [WordPress/twentysixteen#419]
Overall I liked the twentysixteen theme but I have some problem with the search box. If I place the search box on top of the content (right) sidebar, in desktop view anyone can see that easily. But in mobile view the search box comes below 10 full posts. If the posts are of medium or large size, you have to scroll too much to find the search box. It is not also obvious where the get the search box. As search is a very basic and useful operation in blog websites, I think it should appear somewhere on top of the site (may be on configurable basis, whether I want the search box on header or not). You can open my blogsite [http://netontime.com](http://netontime.com) on mobile to see the difficulty. As on mobile I like to show the excerpts of the listed articles instead of full text. Is there anyway to do that?

**Comment by iamtakashi** [comment]
Thanks for your opinion. It maybe a valid opinion with your case but we are not going to add such an option after the release.

Good thing is that you can create a child theme based on Twenty Sixteen to meet your needs. If you need helps on customisation or how to create child theme, it's best to post at https://wordpress.org/support/theme/twentysixteen where most likely to get helps from the community.
