### ISSUE TITLE
Usability: visited and unvisited link colors

### ISSUE THREAD

**Issue by JonathanHayward** [WordPress/twentysixteen#420]
It is my experience that most pages look prettier if all links are the same color. However, in this case being pretty has a significant cost: everything I've read on the matter says it mars usability. I'd mention two UX sources from over the years:

Jakob Nielsen, _Alertbox_, [Top 10 Mistakes in Web Design](https://www.nngroup.com/articles/top-10-mistakes-web-design/), posted 1996 and revisited to keep up to date through 2011:

> Not Changing the Color of Visited Links
> A good grasp of past navigation helps you understand your current location, since it's the culmination of your journey. Knowing your past and present locations in turn makes it easier to decide where to go next. Links are a key factor in this navigation process. Users can exclude links that proved fruitless in their earlier visits. Conversely, they might revisit links they found helpful in the past.
> 
> Most important, knowing which pages they've already visited frees users from unintentionally revisiting the same pages over and over again.
> 
> These benefits only accrue under one important assumption: that users can tell the difference between visited and unvisited links because the site shows them in different colors. When visited links don't change color, users exhibit more navigational disorientation in usability testing and unintentionally revisit the same pages repeatedly.
> 
> [Usability implications of changing link colors](https://www.nngroup.com/articles/change-the-color-of-visited-links/)
> [Guidelines for showing links](http://www.nngroup.com/articles/guidelines-for-visualizing-links/)

Steve Krug, [Don't Make Me Think!](https://www.safaribooksonline.com/library/view/dont-make-me/9780133597271/ch13.html), 2014 revision after original publication in 2000:

> Preserve the distinction between visited and unvisited text links. By default, Web browsers display links to pages that you’ve already opened in a different color so you can see which options you’ve already tried. This turns out to be very useful information, especially since it’s tracked by URL, not by the wording of the link. So if you clicked on Book a trip, when you see Book a flight later you know that it would take you to the same page.
> 
> You can choose any colors you want, as long as they’re noticeably different.

[There has been some change over the years.](https://www.nngroup.com/articles/guidelines-for-visualizing-links/) Nielsen's original stance was that link colors should not be changed from browser default at all. Since then, he revised his position to perhaps still treat different colors as profoundly necessary, but allows non-default color and offers guidance in picking a pair:

>  The color for unvisited links should be more vivid, bright, and saturated than the color for visited links, which should look "used" (dull and washed out).

I was surprised that by default twentysixteen has the same color for visited and unvisited links. I was astonished when I went to customize for an appropriate pair of colors, and found a "choose your poison" offering: I had _total_ control over which one color would be used, and zero facilities short of child theming to opt-in to separate colors. I've begun working a child theme that is maybe 20% artistry and 80% attempts to improve usability, the foremost is by using different colors for visited and unvisited links (I switched to brightish green and subdued brown from importing Chrome defaults). There's a lot to go, and there are known issues, chief among them that the two different colors don't work for the menu. I have also addressed matters that have other UX implications, like increasing the font size for tiny links.

**I would suggest that twentysixteen have different default colors for visited and unvisited links, or at least allow developers to make that choice on an opt-in basis.** I don't think it would be wise to force visited and unvisited links to look different, but I would have the option presented. If I had my way, there would be two color selection widgets, and a checkbox to make them both the same, along with verbiage either giving guidance about choosing colors, and a note that your site might be less pretty but have much less of a frustrating experience if you specify separate colors so the two types of link look different from each other.

I've gotten feedback that... how can explain this... [my work-in-progress website](https://CJSHayward.com) is optimized for less capable users and it should not take so much consideration about how to be usable. I've received a lot of criticisms over the years, but this is the first time I've essentially been criticized for making a website that is simply too usable.

**Comment by ms-studio** [comment]
Indeed, it seems a good idea to allow both _unvisited_ and _visited_ link color to be defined in the theme customizer.

Here's what the WordPress Theme Handbook says about link colors:

https://developer.wordpress.org/themes/advanced-topics/ui-best-practices/#different-link-colors

**Comment by JonathanHayward** [comment]
Thank you; I hope this can make my Wordpress twentysixteen
(twentyseventeen) better!

(-:

On Tue, Feb 9, 2016 at 4:08 AM, Manuel Schmalstieg <notifications@github.com

> wrote:
> 
> Indeed, it seems a good idea to allow both _unvisited_ and _visited_ link
> color to be defined in the theme customizer.
> 
> Here's what the WordPress Theme Handbook says about link colors:
> 
> https://developer.wordpress.org/themes/advanced-topics/ui-best-practices/#different-link-colors
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/WordPress/twentysixteen/issues/420#issuecomment-181794867
> .

## 

[image: Christos Jonathan Seth Hayward] http://jonathanscorner.com/
Jonathan S. Hayward, a full stack web developer with Python/Django and
AngularJS/jQuery.

Articles on Technology http://jonathanscorner.com/technology/ • Book: _Django
JavaScript Integration_
http://www.packtpub.com/django-javascript-integration-ajax-and-jquery/book
 • _Email jsh@jsh.name_ • Github http://github.com/JonathanHayward •
LinkedIn http://www.linkedin.com/in/jonathanhayward • Main Website
http://jonathanscorner.com/ • _Professional Site http://jsh.name/_

I invite you to visit my professional site! http://jsh.name/

**Comment by iamtakashi** [comment]
Thanks for the suggestion. I can see this could be useful for some but it's simply too late :/ We won't be able to introduce an option like this that potentially affects hundreds of thousands sites. This has been open for a month but not getting almost any interests from others either, therefore, I'm concluding it as wontfix.

All functions are pluggable or use filters, so if anyone really wants to implement this in their child themes surely possible.
