### ISSUE TITLE
Boxed or fluid or a good option for both?

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/twentysixteen#43]
What about an option inside the customizer for a choice of boxed or fluid layout?
Perhaps a page template.

**Comment by karmatosed** [comment]
My vote would be we don't add extra things beyond the colours. This isn't a framework we are creating or a starter theme.

**Comment by iamtakashi** [comment]
If I'm understanding correctly this "fluid layout" means here, with the layout, characters per line can be too many to in some cases with wide screens, and that would negatively impact the readability. Also it's generally difficult for users to make it look good with medias that are constrained with `$content_width`. 

Although some users might find it useful in some case, I don't see this option is really valuable for majority of users.
