### ISSUE TITLE
HTML5 input element styling

### ISSUE THREAD

**Issue by shelleyvadams** [WordPress/twentysixteen#437]
style.css doesn't include selectors for the date/time `input[type]`s introduced in HTML5.

``` css
input[type="date"],
input[type="time"],
input[type="datetime-local"],
input[type="week"],
input[type="month"]
```

**Comment by shelleyvadams** [comment]
These two `input[type]` selectors are included in style.css but missing from inc/customizer.php:

``` css
input[type="tel"],
input[type="number"]
```

**Comment by karmatosed** [comment]
What is the reasoning behind this? I'm asking as not every single html element has to be covered and I'm wondering even if we need to. Is there an issue this would fix?

**Comment by shelleyvadams** [comment]
Time and date input elements aren't getting theme styles. When used alongside input elements that do get styled (e.g., `input[type="text"]`) the result is sloppy, inconsistent formatting.

 `input[type="tel"]` and `input[type="number"]` get default theme styles via style.css, but they don't reflect any color changes made in the customizer.
