### ISSUE TITLE
Remove wp_link_pages() from image.php

### ISSUE THREAD

**Issue by jaspermdegroot** [WordPress/twentysixteen#438]
The only way I can think of that an image attachment could be paged is when the description has a `<!-- nextpage -->` tag in it. So I tested if that even works.

On WordPress 4.4 `wp_link_pages()` did indeed print links to pages but when you click on them you get a 404. When I tested with trunk the whole description was printed on the first page and `wp_link_pages()` doesn't print anything. So the `<!-- nextpage -->` tag is ignored in descriptions from now on (which I think is an improvement).

I suggest to remove the `wp_link_pages()` call from image.php.

**Comment by iamtakashi** [comment]
Removing it from this theme doesn't solve anything and this should be reported to core because this isn't a theme issue.

Thanks for the report though.

**Comment by jaspermdegroot** [comment]
@iamtakashi 

Thanks for your reply.

Maybe I didn't explain it very clear. The theme issue that I am reporting is that there is a call to `wp_link_pages()` in the image.php template that is useless.

With core 4.4 `wp_link_pages()` in the image.php template will only print something if you have a `<!-- nextpage -->` tag in your image description, but what it will print is broken links. Those broken links were indeed a core issue but the fix is to ignore the `<!-- nextpage -->` in the description. So with core 4.5 `wp_link_pages()` in the image.php template will never print anything.

**Comment by iamtakashi** [comment]
Thanks for the clarification. I understand `wp_link_pages()` is currently useless and we both agree this is a core issue. 

Considering the fact — all default themes (except Twenty Ten) have `wp_link_pages()` in `image.php`, it could be a regression and this needs to be reported first in core trac before the theme does anything to it even it's useless at the moment.

Once core makes a decision if it's worth to fix or not, and then we act accordingly with the decision.
