### ISSUE TITLE
Logo does not work well in Firefox 45

### ISSUE THREAD

**Issue by gorgoglionemeister** [WordPress/twentysixteen#440]
I uploaded a logo of 1200x175 (the yellow banner in the image) and, in Firefox 45, it does not scale well. It breaks the layout. The viewport is 709px width.

![twentysixteen-709](https://cloud.githubusercontent.com/assets/4553077/13686057/17fb7a8a-e714-11e5-9911-d9cfcef44da7.png)

**Comment by iamtakashi** [comment]
Oh, fun. It looks like there is a difference in implementation of flex box between Chrome and Firefox. We definitely need to fix this.

Thanks for the report!

**Comment by iamtakashi** [comment]
Please test :) Not only different size of logos, but also with a long site title and/or a long menu to check all behaves as expected.

**Comment by gorgoglionemeister** [comment]
Great! Please, I'm sorry but how can I download this new version to test it? I don't know how to use Github very well.

Furthermore, what's the best logo size to fit armoniously in Twenty Sixteen?

Thank you.
