### ISSUE TITLE
Chrome SSL issue

### ISSUE THREAD

**Issue by JosefJezek** [WordPress/twentysixteen#443]
You need remove `http:` from URL...

```
<link rel="profile" href="http://gmpg.org/xfn/11">
```

To

```
<link rel="profile" href="//gmpg.org/xfn/11">
```

**Comment by karmatosed** [comment]
Can you give a little more backstory as to why @JosefJezek - maybe an article or information source?

**Comment by emiluzelac** [comment]
@JosefJezek If you go to https://themeshaper.com, a site that has an SSL enabled

HTTP protocol `<link rel="profile" href="http://gmpg.org/xfn/11">` doesn't throw any issues in Chrome.

![screen shot 2016-04-12 at 14 04 36](https://cloud.githubusercontent.com/assets/1784526/14472236/d33a99fe-00b7-11e6-9527-de7241b766fb.png)

**Comment by iamtakashi** [comment]
The lack of clarification from @JosefJezek, and as @emiluzelac says, I've never seen an issue with what @JosefJezek is referring to. I'm closing this.

**Comment by JosefJezek** [comment]
@emiluzelac Do you have latest version of Chrome?

**Comment by emiluzelac** [comment]
Always do 😉
