### ISSUE TITLE
twentysixteen_categorized_blog() can't be overridden by a child theme

### ISSUE THREAD

**Issue by ocean90** [WordPress/twentysixteen#446]
[The docs are telling a lie](https://github.com/WordPress/twentysixteen/blob/534708502a1b16aa1d7df32d6865af5df158f105/inc/template-tags.php#L194) because the function isn't wrapped by a `function_exists()` check.

**Comment by iamtakashi** [comment]
@ocean90, good catch. I don't see any issue with making it pluggable now. Does the PR above look good to you?

**Comment by karmatosed** [comment]
@ocean90 can we get feedback on this so we can look to merge?

**Comment by ocean90** [comment]
looks good
