### ISSUE TITLE
Embedded Tweet #hashtags and @mentions are same color as background

### ISSUE THREAD

**Issue by chrisaldrich** [WordPress/twentysixteen#448]
When I try to embed a tweet, I notice that the color given to both #hashtags and @mentions is the same as the background of the default twitter background which effectively prevents them from being visible. This appears to be an issue for all of the five base color themes.

Example: http://boffosocko.com/2015/08/04/little-free-library-8424-adams-hill-branch-grand-opening/

**Comment by iamtakashi** [comment]
This isn't the theme issue. It's the way you embed the tweet and it looks like you have a custom link color for the embed. Read the documentation from Twitter and adjust your setting accordingly: https://dev.twitter.com/web/overview/widgets-webpage-properties

**Comment by chrisaldrich** [comment]
Thanks @iamtakashi 

For others stumbling across this, I was apparently (forgetfully) using the official Twitter plugin which allows the specification of the custom colors for the embed as well as a light/dark theme differentiation. It can be found in the dashboard at yoursite.com/wp-admin/admin.php?page=twitter

**Comment by iamtakashi** [comment]
I see. Thanks for sharing that.

It's always good to disable plugins or switch to other theme to verify if an issue is a theme specific issue before reporting an issue.
