### ISSUE TITLE
Should Post Formats be moved?

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/twentysixteen#45]
I know there has been a lot of discussions about Post Formats.
I am just wondering what you think.
Should Post Formats instead be handled in future core plugins like Shortcake? (If my thinking is correct.)

**Comment by karmatosed** [comment]
I think in this case having post formats is fine. We are a bit of a way off any universal replacement option yet - whatever that is or even if someone would use.

**Comment by mor10** [comment]
What is the current function of the post formats in the theme (have not tested). Do they do anything other than function as an added taxonomy?

**Comment by kraftbj** [comment]
I'm still feeling out Twenty Sixteen so I might be wrong, @mor10, but it appears that Post Formats are included in the post meta info that is displayed out of the box.

Within the code, it calls `template-parts/content, get_post_format()`, so a child theme can specify post format specific templates via a `template-parts/content-[format-slug].php`. Nothing specific in stock (at this time).

**Comment by SeanChDavis** [comment]
Yup, that's it. As far as styling goes, all of them (except for the Standard post format, of course) either have smaller entry titles or no [displayed] entry titles at all (Status post format). No other adjustments, though. https://github.com/WordPress/twentysixteen/blob/master/style.css#L2042

**Comment by dshanske** [comment]
What about distinguishing aside from status by displaying the post author avatar on status?

**Comment by karmatosed** [comment]
This issue has a few things on it now. That's ok, but it may be prudent to split things out a bit. On the matter of moving the post formats, we're not planning that. So, in that sense this can be closed.

If people want to open new issues on styling, that is something we'd have up for design review like anything design related.
