### ISSUE TITLE
suggestion for incorporating co-authors

### ISSUE THREAD

**Issue by erathal** [WordPress/twentysixteen#450]
Would be great if somebody could help adding a few lines of code to incorporate Co-Authors Plus template tags into twentysixteen.

Tried to see whether I can think of a solution based on the proposition by Wordpress VIP available [here](https://vip.wordpress.com/documentation/incorporate-co-authors-plus-template-tags-into-your-theme/) , but realised I can't translate this solution 1-to-1 to twentysixteen.

**Comment by iamtakashi** [comment]
@erathal, Twenty Sixteen, as a default theme, is not going to incorporate a third-party plugin like that. You're free to add it into your child theme and if you need a help on that, you'd like to get helps from contributors if you post it in the forum, https://wordpress.org/support/forum/themes-and-templates
