### ISSUE TITLE
Inappropriate position of page-links

### ISSUE THREAD

**Issue by MunifTanjim** [WordPress/twentysixteen#456]
**wp_link_pages()** implementation should be improved. When _Jetpack Sharing_ & _Related Posts_ are used **page-links** is shown at the bottom of everything. But **page-links** should be just below the post content.

This is a screenshot of the incident:
![image](https://cloud.githubusercontent.com/assets/8050659/14630087/0c5a7d2e-062d-11e6-97ec-e56507d40b4d.png)

**Comment by MunifTanjim** [comment]
Implementing **wp_link_pages()** like this should solve the problem:

```
add_filter( 'the_content', 'add_wp_link_pages' ); 
function add_wp_link_pages( $content ) {
  $wp_link_page = wp_link_pages( array(
    'before'      => '<div class="page-links show"><span class="page-links-title">' . __( 'Pages:', 'twentysixteen' ) . '</span>',
    'after'       => '</div>',
    'link_before' => '<span>',
    'link_after'  => '</span>',
    'pagelink'    => '<span class="screen-reader-text">' . __( 'Page', 'twentysixteen' ) . ' </span>%',
    'separator'   => '<span class="screen-reader-text">, </span>',
    'echo'        => 0,
  ) );
  $content = $content . $wp_link_page;
  return $content;
}
```

**Comment by karmatosed** [comment]
I feel where page-links are shown is up to the theme design. There is no rule. @iamtakashi what do you think on this?

**Comment by karmatosed** [comment]
I am closing this as do not believe this is something wrong with the theme as much as a choice by the designer in this case.
