### ISSUE TITLE
Remove deprecated tags

### ISSUE THREAD

**Issue by grappler** [WordPress/twentysixteen#457]
Related: https://core.trac.wordpress.org/ticket/33407

For this theme we can add the tag `blog` also

The final list would be: `one-column, two-columns, right-sidebar, accessibility-ready, custom-background, custom-colors, custom-header, custom-menu, editor-style, featured-images, flexible-header, microformats, post-formats, rtl-language-support, sticky-post, threaded-comments, translation-ready, blog`

I will create a PR if this is OK.

**Comment by karmatosed** [comment]
Absolutely, please create one @grappler
