### ISSUE TITLE
Menus: Dropdown menus open off-screen

### ISSUE THREAD

**Issue by melchoyce** [WordPress/twentysixteen#458]
When your primary navigation menu is long enough to drop down to its own line, and the first menu item you have contains child menu items, the dropdown menu opens off-screen:

<img width="1267" alt="screen shot 2016-04-22 at 10 25 28 am" src="https://cloud.githubusercontent.com/assets/2846578/14744384/9246757a-0874-11e6-8b77-0f5783ff4c6e.png">

You can see it in action on https://2016.rhodeisland.wordcamp.org. I was also able to duplicate on my test site.

**Comment by josephfusco** [comment]
Hey @melchoyce, @iamtakashi made a the decision not to fix this in https://github.com/WordPress/twentysixteen/issues/321.

**Comment by iamtakashi** [comment]
@josephfusco is correct. My comment [here](https://github.com/WordPress/twentysixteen/issues/394#issuecomment-162731502) sums up my conclusion on this matter.

**Comment by melchoyce** [comment]
I keep seeing this issue pop up on different WordCamp sites. Surely there's something we could do?
