### ISSUE TITLE
Menu now aligned right instead of left

### ISSUE THREAD

**Issue by ghost** [WordPress/twentysixteen#459]
On my website askamiga.com. This is since today's update.

**Comment by josephfusco** [comment]
@tenleftfingers Which menu? You linked your site but can you please provide more details?

You do have quite a few plugins active loading their own stylesheets. Have you tried deactivating them and reactivating one by one to see if the issue remains?

**Comment by ghost** [comment]
@josephfusco I mean the top menu bar with the three entries; AskAmiga, FAQ and Login. The plugins existed before the update to Twenty Sixteen update but I'll try disable some of them and see. Thanks.

**Comment by ghost** [comment]
I disabled all plugins and refreshed but it's the same. I've re-enabled them again now but they were definitely disabled as there was not much to see on the site without them :)

**Comment by iamtakashi** [comment]
The main navigation has always been aligned to the right in this theme unless there are many menu  items or the site title is long enough to push the menu down.

You can see the demo site here: https://twentysixteendemo.wordpress.com/

The alignment hasn't been changed with the last update and we have't heard an issue like this. Therefore I'm closing this as "worksforme".
