### ISSUE TITLE
Add theme releases to releases section.

### ISSUE THREAD

**Issue by josephfusco** [WordPress/twentysixteen#460]
There are currently no releases present within the GitHub repo for this theme:
[https://github.com/WordPress/twentysixteen/releases](https://github.com/WordPress/twentysixteen/releases)

You can see them in use for WordPress:
[https://github.com/WordPress/WordPress/releases](https://github.com/WordPress/WordPress/releases)

**Comment by karmatosed** [comment]
We don't currently use releases @josephfusco as the theme is hosted on .org theme repo. I think as a result this is the way that things will work for us.
