### ISSUE TITLE
Blockquote styling looks odd with image floated left

### ISSUE THREAD

**Issue by ericandrewlewis** [WordPress/twentysixteen#462]
<img width="863" alt="screen shot 2016-04-27 at 8 52 41 pm" src="https://cloud.githubusercontent.com/assets/1087646/14872407/0ba6ec12-0cba-11e6-9617-e026cce21735.png">

**Comment by iamtakashi** [comment]
Do you have a URL where I can see the issue? Or can you provide the html for the content to reproduce this?

**Comment by ericandrewlewis** [comment]
Sure, here's some html

```
<img class="alignleft" src="http://media2.popsugar-assets.com/files/2015/03/09/043/n/1922398/3ed22f08_edit_img_cover_file_1884259_1425944500_IMG_6085xIkaBk.xxxlarge/i/Affordable-Neon-Signs.jpg" width="282" height="188" />

Test content
<blockquote>Blockquote here</blockquote>
Another paragraph
```

**Comment by iamtakashi** [comment]
Thanks. One way to fix the issue is to apply `overflow: hidden` to `blockquote` but we need to test.

**Comment by josephfusco** [comment]
This will work but Safari handles that clearfix differently.

## Chrome/Opera/Firefox

![screen shot 2016-04-29 at 11 29 32 am](https://cloud.githubusercontent.com/assets/6676674/14920984/d35e7966-0dfd-11e6-846b-b6aa1009ebab.png)

## Safari

![screen shot 2016-04-29 at 11 31 05 am](https://cloud.githubusercontent.com/assets/6676674/14921004/e886a55c-0dfd-11e6-8b57-82034915da7d.png)

**Comment by iamtakashi** [comment]
Thanks for testing. Good to know. Safari's quirks is a headache but if this fixes for a majority of users, we should go for it. How about IEs?

**Comment by josephfusco** [comment]
## Edge/IE11/IE10/IE9

![edge](https://cloud.githubusercontent.com/assets/6676674/14921814/1ec04a16-0e02-11e6-99bf-9f684bf9f95a.PNG)

## IE8

![ie8](https://cloud.githubusercontent.com/assets/6676674/14921821/23a0169c-0e02-11e6-8c25-1d5d36e15d04.PNG)

**Comment by josephfusco** [comment]
- Note this same issue exists in Twenty Fifteen as well.

**Comment by karmatosed** [comment]
@josephfusco do you want to open a ticket and add a patch for Twenty Fifteen?
