### ISSUE TITLE
On single-author blogs, forward slash appears before post date

### ISSUE THREAD

**Issue by sarahmonster** [WordPress/twentysixteen#467]
I'm not sure if this is a bug or intended behaviour, but it feels rather like a bug so I figured I'd file it. :)

<img width="643" alt="screen shot 2016-05-11 at 13 35 21" src="https://cloud.githubusercontent.com/assets/376315/15181169/94d1f4be-177d-11e6-95a9-b47111ffd2ef.png">

The CSS is trying to add the forward slash before any span elements in the footer that aren't the first child of the footer element: 

`.entry-footer > span:not(:first-child)::before`

Trouble is, on a single-author blog, the first element (.byline) is hidden, but it still counts as the first element, so you get this unanticipated behaviour. 

This only occurs at tablet breakpoints (980px) and below.

**Comment by philiparthurmoore** [comment]
@sarahmonster, looks like this was already taken care of in https://github.com/WordPress/twentysixteen/pull/404/commits/02281f4a4a843c99f3a5b7a31f8f51a65639eaf8.

**Comment by sarahmonster** [comment]
Ah, lovely, thank you! We must be running an out-of-date version.
