### ISSUE TITLE
Google Fonts - feature request

### ISSUE THREAD

**Issue by DecimusBurton** [WordPress/twentysixteen#469]
What I'd love to see in Twenty Sixteen and going forward to Twenty Seventeen would be the ability to globally change the font pairs.  Its possible to do with a plugin like Easy Google Fonts.... but still requires quite a lot of fiddling about.  It would be so cool if it could be done under customisation settings where you set the Primary and Secondary fonts for the font pairs

**Comment by karmatosed** [comment]
This would actually be something I'd advise you have in a child theme or plugin. It wouldn't be something we'd add to a core theme, but thanks for your suggestion.

**Comment by DecimusBurton** [comment]
Its something loads of people ask about - yes it can be done via plugins
like easy google fonts - but for most non-techies there is still a truck
load of css selctors that you manually have to change.

There are sites like http://fontpair.co/ that help you choose font
pairings.

How cool would it be to be able under the customisation settings to be able
to change the  to font pair and for everything then to change without the
headache of finding ALL the css selectors to manually change?

I don't think you should write this suggestion off so quickly.

PB

On 10 June 2016 at 21:09, Tammie Lister notifications@github.com wrote:

> Closed #469 https://github.com/WordPress/twentysixteen/issues/469.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/WordPress/twentysixteen/issues/469#event-689050960,
> or mute the thread
> https://github.com/notifications/unsubscribe/AF2tAYplGT5S0pNjNnklc2L54tKD6_Jqks5qKcRxgaJpZM4Iu_ms
> .

## 

Peter E Burton 巴培德
e-mail: peter.burton@decimus.com
UK mobile: +44 (0)787 261-0026
UK home: +44 (0)1372 451-706

## HK mobile: +852 9315-1181

## skype: decimus_burton

UK address:  Ranmore, Beech Avenue, Effingham, Near Leatherhead, Surrey

## KT24 5PJ, UK

Email Disclaimer: The information in this email is confidential and may be
legally privileged. It is intended solely for the addressee.

**Comment by karmatosed** [comment]
@DecimusBurton I'm not dismissing without thought quick. This is exactly why having options like plugins and child themes is amazing.

**Comment by DecimusBurton** [comment]
I know I guess what I am saying is that is you are very tech orientated....
what we are seeing on the group is lots of non techies using this wonderful
tool.  Most of them do not have the skills to do child schemes.  The
changing of the font pairs significantly changes the look and feel.  It's
more relevant now that Google has put Google fonts into the public domain.

It's a thought I leave with....

Peter Burton - sent from phone
peter.burton@decimus.com
+44 787 261 0026
+852 9315 1181

**Comment by brentlogan** [comment]
@DecimusBurton, I actually come down on the opposite side of this issue. I'd love for the default theme _not_ use Google fonts. But there are plugins that help there, too. 

One plugin you might one to look into that addresses font pairs is [Styleguide](https://wordpress.org/plugins/styleguide/). No filddling about needed. It supports multiple themes, including all the default WordPress themes, and the author has been responsive to requests. Sorry if this sounds like an add, but I've been a satisfied customer and it's one data point that supports @karmatosed's point.
