### ISSUE TITLE
Add or not to add....

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/twentysixteen#47]
Hey

Ideas will come up that are really good but for whatever reason are not be added to the official theme.
So what if an underground unofficial theme is created at the same time? 
To showcase various things the official theme chooses not to showcase. It will show more variation of what can be done and can be used for further study for various users.

**Comment by karmatosed** [comment]
I'm not totally sure this needs to be an issue. Anyone can make any theme they want. Some focus is needed to make sure we get this developed. I've tagged it for discussion, but will close for now.
