### ISSUE TITLE
Change log

### ISSUE THREAD

**Issue by henrywright** [WordPress/twentysixteen#476]
Does Twenty Sixteen have a change log? Unlike Twenty Fifteen, there doesn't seem to be a section in readme.txt.

**Comment by karmatosed** [comment]
We have one in readme.txt

**Comment by henrywright** [comment]
> We have one in readme.txt

I see you committed a change log to readme.txt 42 minutes ago:

https://github.com/WordPress/twentysixteen/commit/0bd360d67791e833ce1590e924e5799a54d6a437

Many thanks!
