### ISSUE TITLE
Consider changing the max width of TinyMCE for HiDPI screens

### ISSUE THREAD

**Issue by dsifford** [WordPress/twentysixteen#483]
Hi there. This isn't really a bug, but I figured I'd toss the idea your way nevertheless.

The `max-width` of the TinyMCE editor is set at 600px, which is definitely appropriate in most cases, but looks strange when using a HiDPI monitor.

![image](https://cloud.githubusercontent.com/assets/5240018/17538772/745b1874-5e76-11e6-87b8-bd5b914a4919.png)

Possibly consider changing the max-width in those cases? Or possibly using a % value?

Thanks either way. 👍

**Comment by josephfusco** [comment]
@dsifford I think it is like this to match how it will appear on the front end of the site. While it may look odd at that screen size, it is a better representation of it's outputted appearance like this.

**Comment by dsifford** [comment]
@josephfusco Ah, hadn't thought of that. I suppose that does make sense. Disregard! 😊
