### ISSUE TITLE
Skip link not working correctly on mobile

### ISSUE THREAD

**Issue by alexstine** [WordPress/twentysixteen#488]
When using an IPhone5C with Voiceover, the Skip To Content link is not working. Once the link is clicked, it goes to "contentinfo"/"`<footer>`" instead of "content" as "#content" directs it to do. Seems to work fine visually, but with Voiceover it focuses on the first item of the footer navigation menu.

Can we please get this one patched up? Site is not fully working, quick fix available?

**Comment by davidakennedy** [comment]
Closing this, as the ticket in Core is closed. See: https://core.trac.wordpress.org/ticket/38338#comment:16
