### ISSUE TITLE
Black border should be easier to disable

### ISSUE THREAD

**Issue by songproducer** [WordPress/twentysixteen#489]
I've spent many hours of frustration on multiple websites trying to css hack the border out. I succeeded on the first one but am spending far too long unsuccessfully on the second one.

I realise the colour can be changed, but then there would still be padding that I'd rather not have there.

Can someone please make a toggle option?

**Comment by karmatosed** [comment]
@songproducer at this time, I think having it as a toggle doesn't work as that adds a theme option. This is a design decision for this theme. You can always use Custom CSS or make a child theme to remove this.
