### ISSUE TITLE
Add RTL language support

### ISSUE THREAD

**Issue by iamtakashi** [WordPress/twentysixteen#5]
- Add `rtl.css`
- Add `rtl-language-support` tag to both `style.css` and`readme.txt`

**Comment by mathetos** [comment]
I submitted a PR with a functional RTL.css file here: https://github.com/WordPress/twentysixteen/pull/54

I didn't add tags in `styles.css` or `readme.txt` though.

**Comment by iamtakashi** [comment]
Thanks for the PR but as grappler said in the PR, it'd be better to leave this until much later on the development because the theme's CSS is expected to change.

**Comment by mathetos** [comment]
No worries, makes sense.

**Comment by karmatosed** [comment]
We discussed this in this week's meeting. This is now a scheduled task to add at the final stages. We do this because the CSS may change.

**Comment by iamtakashi** [comment]
Done!
