### ISSUE TITLE
Work on old IE version specific stylesheets

### ISSUE THREAD

**Issue by iamtakashi** [WordPress/twentysixteen#6]
Layout doesn't need to be exactly the same but let's make it at least readable and usable on IE7 and above.

**Comment by obenland** [comment]
I talked to @helenhousandi about dropping support for IE8 in core. Twenty Sixteen seems like a good reason to follow through on that and not worry about outdated IEs anymore.

**Comment by war59312** [comment]
"Starting on January 12, 2016, Internet Explorer 11 will be the minimum supported version to continue to receive security updates and technical support on Windows 7 and Windows 8.1."

Source: http://blogs.windows.com/msedgedev/2015/08/26/how-microsoft-edge-and-internet-explorer-11-on-windows-10-work-better-together-in-the-enterprise/

Just saying.. Perhaps only support IE 11 then?

**Comment by ihorvorotnov** [comment]
We should drop <IE8 completely and care about more useful stuff, like better default fonts (see #30).

**Comment by helen** [comment]
Browser support for admin and browser support for bundled theme don't necessarily have to match, as they have different goals. Browser support can also be defined in a lot of different ways. For the admin, we want to empower as many people as possible to publish, so we have some soft guidelines around older browsers (e.g. don't crash IE7 completely, things should be legible/navigable in IE8 and also not crash it but don't have to look "pretty").

Themes, on the other hand, are more about the audience - the site admin should be able to use a theme with the type of support that best fits their needs. I think it's fine not to bother supporting old browsers with Twenty Sixteen, although I would suggest that it be decided whether old browser support is actively or passively dropped (checked on and warned against vs. just not bothering checking at all).

**Comment by peterwilsoncc** [comment]
@helenhousandi does the WordPress project have a preferred source for global stats? The big few providers differ somewhat.

My inclination is the check against IE8 and above; with an IE8 pass being not crashing. All Windows desktop and server environments can upgrade to IE8, there are some POS systems stuck on IE7.

Depending on resolution of this ticket, blocks with CSS3 selectors mixed with <= IE8 compatible selectors will need to be split to prevent IE dropping the entire block. As it stands IE8 will drop all of the following:

``` css
.sticky .posted-on,
.byline,
.updated:not(.published) {
    display: none;
}
```

**Comment by helen** [comment]
@peterwilsoncc I don't have one, and I don't know of a declared preferred source. I don't think global stats mean a whole lot, FWIW - for sites/themes it really should be dependent on the stats of the site itself, for core it's taking into consideration the types of users who are on these older browsers, e.g. if IE8 usage is low globally but a large percentage of its own usage is public sector (libraries, government), then we should probably continue to care about it at least somewhat.

**Comment by peterwilsoncc** [comment]
Thanks Helen, I'll work on the basis of IE8+ for any further patches.

**Comment by mor10** [comment]
Based on WordPress' global reach and the fact that outside North America, Europe, and the more developed areas of the world, most people are still stuck with ageing technology and slow internet connections, phasing out IE8 is not advisable. There are still far too many people who rely on WordPress that are on computers with IE8.

**Comment by ihorvorotnov** [comment]
According to [this 2014-2015 stats](http://gs.statcounter.com/#all-browser_version_partially_combined-ww-monthly-201408-201507) I see IE8 phasing down from 3.34% to 1.55% **globally**. IE9 and IE10 are less than 1%. 

Let's see the stats for some "less developed areas":

**Africa**. IE8 = 1.11%
**Antarctica**. IE8 falls into "Other category" :) (which is 1.79% combined)
**Asia**. IE8 = 1.63%

Let's drill deeper and choose some random "less developed countries":

**Belarus** (Eastern Europe, ex-USSR, kind of dictatorship). IE8 = 1.91%
**Botswana** (you know, Kalahari desert and stuff like that). IE8 = 2.53%
**Bolivia** (one more desert, mountais, rainforest etc). IE8 = 2.4%
**India** (apart from $3/h devs it's far from being "developed"). IE8 falls into barely noticeable "Other category"
**Tajikistan** (mountains, ex-USSR). IE8 = 0.8%
**Viet Nam** (rapidly developing asian economy). IE8 = 5.31% (however, the graph is pretty strange - month ago it was 2.9%)

And, **the US** - IE8 = 1.84%

I don't see any signs of "most people are still stuck with ageing technology". 

As for the connection speed - I was surprised how **slow** (!) it is over United States (and some places in western Europe). For example, right now I'm visiting my parents in a small city in western Ukraine, in a city with ruined economy (it was a mining city back in USSR). And I'm on a 100Mb cable connection which costs $5/month (100Mb internet with unlimited bandwidth + almost 100 cable TV channels). Some people use 50 or 20Mb plans, they are cheaper. And this is _normal_ for a developing country called Ukraine, we have this internet available all over the country from many providers, it's highly competitive market. I know the same about many, many developing countries. The truth is, it's easier and cheaper to build a new 100+ Mb network in a developing country than to upgrade / replace existing, old, slow networks in developed countries. You can find some stats online, US is not in top-10 countries :) And so are most of the european "developed countries".

My point is, there's no difference if it's Manhattan or an egyptian desert - **IE8 and below are definitely dead**. Stop trying to revive the old man. 

Let. Them. Go. Gracefully. (C) Geoge Carlin

**Comment by ianstewart** [comment]
A sum up of the soft guidelines above.

IE7

-don't crash IE7 completely

IE8
- things should be legible/navigable in IE8
- and also not crash it
- but don't have to look "pretty"

Could use some screenshots/GIFs here of the what that looks like for Twenty Sixteen. And a confirmation that we're not crashing IE7. :)

**Comment by karmatosed** [comment]
Noting that we have this PR: https://github.com/WordPress/twentysixteen/pull/226

**Comment by iamtakashi** [comment]
OK, it should look ok in old IEs. The intended look in IE8 and 7 is basically the style we use for portrait tablets.

![twentysixteen-ie8 7](https://cloud.githubusercontent.com/assets/908665/10059751/b4faa07c-6244-11e5-9ccb-f2cfa72ea97e.png)

I'll close this issue as the work for the ticket is done but we can file new issues if we find bugs.
