### ISSUE TITLE
A non-idiosyncratic screenshot

### ISSUE THREAD

**Issue by ianstewart** [WordPress/twentysixteen#63]
Perhaps with a nice picture? My eye seems to be consistently drawn to the peculiar stuffed potato dumplings at the Renfield. :) Perhaps something that fades in the background? More "common" like last year? A photo of a place, a title related to that photo, and some more "abstract" text?

![](https://i0.wp.com/themes.svn.wordpress.org/twentyfifteen/1.3/screenshot.png)

**Comment by iamtakashi** [comment]
@ianstewart Yes, we can make it more abstract. Are you thinking with a featured image?

**Comment by ianstewart** [comment]
Maybe a post image instead of a featured image since it'd likely be the most common scenario (for a post with an image.)

**Comment by iamtakashi** [comment]
I'll work on it.

**Comment by iamtakashi** [comment]
A new screenshot:

![screenshot](https://cloud.githubusercontent.com/assets/908665/10179722/cd2bf1a4-66ff-11e5-9749-2e4336eeaed2.png)
