### ISSUE TITLE
Add styles for code tag

### ISSUE THREAD

**Issue by mkrdip** [WordPress/twentysixteen#70]
By default `<code>` selector has no CSS style defined. Screenshot:

![image](https://cloud.githubusercontent.com/assets/3819579/9593012/764e44f4-506b-11e5-88f9-cc4b99819b43.png)

It's nice to have a style for the `<code>` selector with a background color & some padding. Screenshot:

![image](https://cloud.githubusercontent.com/assets/3819579/9593038/bc0da8f4-506b-11e5-939a-f791264083fb.png)

**Comment by iamtakashi** [comment]
@mkrdip, I like the idea but your PR is incomplete.
- The unit for the padding should be `em` in the main stylesheet.
- No correspondence change in the editor stylesheet.
- The background color should change accordingly with the color scheme option.

I'll work on a new patch.
