### ISSUE TITLE
Improper Microformats for Excerpt

### ISSUE THREAD

**Issue by dshanske** [WordPress/twentysixteen#72]
The microformats class for an excerpt is entry-summary, not entry-intro.

http://microformats.org/wiki/hatom

**Comment by metodiew** [comment]
Does it mean that all  `entry-summary` instances needs to be replaced with `entry-intro`?

**Comment by dshanske** [comment]
The other way around.

**Comment by metodiew** [comment]
Thanks @dshanske! I shouldn't have commented before the coffee :)

**Comment by iamtakashi** [comment]
@metodiew, have you tested before and after of your change? `.entry-intro` is supposed to have different style than `.entry-summary`. I assume, by looking at your commits, you didn't realised about it.

I'll work on a PR.

**Comment by metodiew** [comment]
Well, at first I didn't noticed the difference, but I've tested it one more time now and I saw a few issues/differences, not sure what happened the first time...
I don't mind closing the PR if it's far from what needs to be updated here :)

**Comment by dshanske** [comment]
This is why styles shouldn't be attached to Semantic markup such as microformats. Better to keep them separate.
