### ISSUE TITLE
Folder structure for minified scripts and/or styles

### ISSUE THREAD

**Issue by pattonwebz** [WordPress/twentysixteen#77]
I would like to discus what the file and folder structure might look like if the theme included minfied versions of styles and scripts as well as non-minified versions when as the theme progresses.

It may not be the best time to include these right now but closer to completion I think that minified versions should be included for sure.

With merge of PR #61 all files in the theme are currently non-minified. For production I would suggest that using minified files would be preferential but the issue would be how to do that.

My suggestion is to have minified versions of each script inside the same folder as the non-minified versions. As for the stylesheet - it may not be the best idea to include style.min.css in the root alongside the standard style.css but I still think providing a minified version would be of benefit.

What does everyone think about where minified files should be placed and how they should be enqueued? Should they only be enqueued conditionally by choice of the user... Is that too complicated an option for a default theme?

**Comment by karmatosed** [comment]
I don't really see a new structure needed for minified. We can have both in the same file. I absolutely do not think we need to minify style.css. Only one we could is .js.

**Comment by pattonwebz** [comment]
Agreed that if files were minified it would be ideal to include them in the same directory alongside the original. 

If .js files were to be minified should they first be combined and then that file minified into `scripts.min.js` or similar? Or should they be minified and enqueued individually?

**Comment by ihorvorotnov** [comment]
@pattonwebz People use a lot of different plugins to handle concatenation and minification. Many caching plugins have this feature built-in. I believe we should not force any concatenation (this is for user to decide). As for the minification - in my development I always have both versions (in two folders - dev and min), enqueuing proper file depending on environment (non-minified for local and dev server, minified for production). However, I believe it's too complicated for end users, the theme package in WP.org repo should have only minified files.

**Comment by mtomas7** [comment]
"the theme package in WP.org repo should have only minified files" - it is against WP.org Theme Check team rules - every minified version should include real version.

**Comment by ihorvorotnov** [comment]
@mtomas7 my bad, I meant minified files should be enqueued by default, without any additional dev/prod switches like I use in my projects.

**Comment by karmatosed** [comment]
I think this should be closed as we won't be including minified versions of css and the minified js can just be in the normal folder. A simpler folder structure helps people understand.
