### ISSUE TITLE
Screen looks like a notice about someone's death

### ISSUE THREAD

**Issue by MonikaTS** [WordPress/twentysixteen#81]
at Austria we use a big black border for notices about someone's death. I was really shocked as I've seen the screen of twenty sixteen the first time.
The bold black headlines and bold black borders complement this.

I know this is the background, but the initial visual impact was shocking. 
![screenshot-twenty-sixteen_mini](https://cloud.githubusercontent.com/assets/12694170/9605124/189adfec-50bc-11e5-9cf3-154d3a144f35.jpg)

**Comment by iamtakashi** [comment]
I must admit that I didn't know about it.

However, this is a design choice and you can simply change the colour.
