### ISSUE TITLE
Add Post Title to edit_post_link for Improved Accessibility

### ISSUE THREAD

**Issue by davidakennedy** [WordPress/twentysixteen#82]
One small tweak we could make to improve the accessibility of Twenty Sixteen is adding the post title to the `edit_post_link` and hiding it with `screen-reader-text`. We do this in a few other spots to provide more context to link text, and the case would be the same here.

Thoughts?

Pull request incoming. :smile:

**Comment by karmatosed** [comment]
I've merged this, thanks.
