### ISSUE TITLE
Wrong Number of location above register_nav_menus on functions.php

### ISSUE THREAD

**Issue by arryaas** [WordPress/twentysixteen#83]
There is Wrong Number of location above register_nav_menus on functions.php in line number 71

**Comment by ihorvorotnov** [comment]
There's a PR https://github.com/WordPress/twentysixteen/pull/68 and duplicate issue #67

**Comment by arryaas** [comment]
@ihorvorotnov , @iamtakashi can I fix this issue? I am not being able to pull request

**Comment by ihorvorotnov** [comment]
@arryaas What do you mean by fixing this? There's already a PR #68 with a fix. It will do the job once the PR is accepted by @karmatosed 

Here's the fix: https://github.com/tywayne/twentysixteen/commit/5f8b9eb55101afe0538933d29812d175c02dae27

**Comment by arryaas** [comment]
@ihorvorotnov I think wp_nav_menu() is used in four locations. Two on there footer and two on header . Sorry If am mistaken.

**Comment by ihorvorotnov** [comment]
@arryaas the same menu can be used many times in templates. For example, you can add a menu widget to your sidebar and have one more instance of the same nav menu. But the `register_nav_menus()` actually registers 2 menu locations - `primary` and `social`. I guess you're misguided by the "location" term.

**Comment by arryaas** [comment]
@ihorvorotnov 
May be my mistake I just compared with twentyfifteen functions.php. There is written 2 location but used on 1 file 2 times.
