### ISSUE TITLE
Function ending comment missing

### ISSUE THREAD

**Issue by arryaas** [WordPress/twentysixteen#85]
Function ending comment are missing on different file.

**Comment by iamtakashi** [comment]
Can you be more specific and providing details when you make an issue? This is not very helpful at all.

**Comment by arryaas** [comment]
Like in some function there is comment at closing:

```
if ( ! function_exists( 'twentysixteen_sanitize_color_scheme' ) ) :
---
endif; // twentysixteen_sanitize_color_scheme
```

but on some there are not:

```
if ( ! function_exists( 'twentysixteen_fonts_url' ) ) :
---
endif;
```

Sorry if it is not helpful.

**Comment by ihorvorotnov** [comment]
Well, that's pretty subjective thing, IMHO. How long / complicated a function should be to have a closing comment? Adding it to every function is obviously an overkill.

**Comment by iamtakashi** [comment]
I meant the overly generic description about the issue wasn't helpful. You could at least specify file names and function names you see the issue so that we can look at it. Otherwise we need to review every functions in every files, don't we?

**Comment by arryaas** [comment]
@iamtakashi yes you are absolutely right. I am new at this and am learning. Also want to make tiny contribution here. 

and, I have a question, should there be @ since  in function comment or not?

**Comment by karmatosed** [comment]
@arryaas knowing which file and having a PR would be great for this.

**Comment by karmatosed** [comment]
Ideally we need to know which files this is in, until we do I will close this.
