### ISSUE TITLE
Rename `custom-header.php` to more suitable name

### ISSUE THREAD

**Issue by wenthemes** [WordPress/twentysixteen#9]
As now `custom-header.php` contains functions for both Custom Header and Custom Background, may be we should rename it to more suitable name.

**Comment by fklein-lu** [comment]
We should probably move these functions to `functions.php`.

**Comment by karpstrucking** [comment]
this file is required from within `functions.php`, presumably to keep `functions.php` lean and code segmented. if anything, `custom-header.php` could be moved into `customizer.php` but is probably fine to leave alone as well.

**Comment by ihorvorotnov** [comment]
It should stay in a separate file, in `inc` folder. Not all users need it, removing support by simply commenting one line is a good solution used by many themes (and _s). It's an optional feature.

I tend to agree with @karpstrucking, moving Customizer features to `customizer.php` sounds logical.  However, as we build more and more features for Customizer, the file is going to be large and hard to maintain. It actually is 1000+ lines now. Maybe, it makes more sense to have smth like this:

`/inc/customizer.php` - general code
`/inc/customizer-custom-header.php` - custom header code
`/inc/customizer-color-themes.php` - color themes
`/inc/customizer-SOME-FEATURE.php` - some other feature

**Comment by iamtakashi** [comment]
Currently `custom-header.php` has just under 100 lines. I personally don't mind to move it to `customizer.php` if we want to keep the logic some mentioned.

**Comment by ihorvorotnov** [comment]
@iamtakashi `customizer.php` is over 1000 lines already.

**Comment by ianstewart** [comment]
The consensus in core-themes was to just bring this into customizer.php:

https://wordpress.slack.com/archives/core-themes/p1441383329000269

**Comment by iamtakashi** [comment]
Fixed via #109
