### ISSUE TITLE
Sticky post with no title and featured image

### ISSUE THREAD

**Issue by maharzan** [WordPress/twentysixteen#98]
When there is no title and no featured image in the sticky post, we cannot go to that individual post as there is no date and the "featured" text isn't linked as well. Not sure how to fix but maybe we can add a link to Featured text or add the date back. maybe an edge case..

**Comment by iamtakashi** [comment]
I think this is really an edge case and it doesn't worth to complicate the logic of post meta. The whole content is visible on index and people can access to comments with a comment link anyway.

Twenty Fifteen works the same way and AFAIK there isn't a complain about it.

**Comment by maharzan** [comment]
Cool. I thought so.. Sometime back this was a major issue and themes wouldn't pass on wordpress.org. :-)
